Feature/goals bar text
plausible/analytics pull request #1165
Opened 2021-07-06 04:42 UTC by hirusi

### Changes

This fixes two issues from #972:

- Goals area has display issues depending on the name of your custom events
- It is not possible to view labels for outbound links, 404 and custom props

### Tests
- [x] This PR does not require tests

### Changelog
- [ ] Entry has been added to changelog

### Documentation
- [x] This change does not need a documentation update

2021-07-06 04:50 UTC, hirusi commented
PR is up-to-date with the latest `master`.

2021-07-06 13:06 UTC, ukutaht requested changes

2021-07-06 13:06 UTC, ukutaht commented on assets/js/dashboard/stats/pages/entry-pages.js
> +          maxWidthDeduction="4rem"
Looks like you're giving more space for the Bar components in the Devices tab. I'm assuming that's because these reports also show a percentage so there's less space for the bar.

I would prefer to be completely consistent with these so there are only two 'sizes' for the Bar component. Bigger one for the Conversions report and a smaller one for all others. The Bar component could default to the smaller size so the `maxWidthDeduction` would only have to be passed from the bigger components. What do you think?

2021-07-06 13:06 UTC, ukutaht commented on assets/js/dashboard/stats/conversions/index.js
> +            text="dark:text-gray-300"
Why does only this one Bar need a different text color?

2021-07-06 13:12 UTC, ukutaht commented on assets/js/dashboard/stats/conversions/index.js
> +        <Link to={{pathname: window.location.pathname, search: query.toString()}} className="block px-2 py-1.5 hover:underline relative z-9 break-words">
Missing a text color override for dark mode: 
![Screenshot from 2021-07-06 16-12-15@2x](https://user-images.githubusercontent.com/3731516/124605809-f866ee80-de74-11eb-90ac-eda161f7d479.png)

2021-07-07 04:55 UTC, hirusi commented on assets/js/dashboard/stats/conversions/index.js
> +const FALLBACK_WIDTH = 639
Interesting. I reviewed this again too after you brought it up and looks like we may not need it at all. At least, not in these two components for conversions.

2021-07-07 04:57 UTC, hirusi commented on assets/js/dashboard/stats/conversions/index.js
> +            text="dark:text-gray-300"
Hmm, good question. Might need to default the dark color, also taking into account https://github.com/plausible/analytics/pull/1165/files#r664542615.

2021-07-07 04:57 UTC, hirusi commented on assets/js/dashboard/stats/conversions/index.js
> +            content={this.renderGoalText(goal.name)}
Correct. You're right here too! My React is a bit rusty. This is an obvious improvement. :)

2021-07-07 05:00 UTC, hirusi commented on assets/js/dashboard/stats/pages/entry-pages.js
> +          maxWidthDeduction="4rem"
For the most part, I have simply copied down whatever the max width deduction was already being made for any given component. I haven't taken a look at them holistically.

The only new value I have introduced for max width deduction is a 10rem, down from 16rem, in conversions on mobile view, where one more column is removed and the bar is free to take up more space on account of this column removal.

From what I can from the commit, there appear to be three values now in total: 4rem, 16rem, and 10rem. We can probably standardize 4rem as the default since that one repeats the most.

What do you think?

2021-07-07 07:37 UTC, ukutaht commented on assets/js/dashboard/stats/pages/entry-pages.js
> +          maxWidthDeduction="4rem"
Ah OK. For some reason I thought this was something you introduced in this PR. No need to worry about it then, I can also take a look later :)

2021-07-07 07:39 UTC, ukutaht commented on assets/js/dashboard/stats/conversions/index.js
> +            text="dark:text-gray-300"
I checked again and it seems like this doesn't do anything. It sets the `color` property on the bar itself (not the text in it). Since the bar is colored using `bg-color` anyways, this should not affect anything.

I'm pretty sure the `text` property can be safely deleted.

2021-07-08 06:41 UTC, ukutaht approved these changes

2021-07-08 06:42 UTC, merged

2021-07-08 06:42 UTC, ukutaht commented
Amazing, thank you @hirusi!