Import of historical data
plausible/analytics pull request #1466
Opened 2021-11-12 17:39 UTC by m-col

### Changes

As a bit of an update, here is the current state of my work on importing data from Google Analytics (as a first step - generic CSV input to be added later).

My ongoing to do list:

- [x] Add import panel to general settings page
- [x] Use existing google auth setup to get access to GA data
- [x] Fetch GA data via Reporting API (currently just getting visitors for main graph)
- [x] Insert visitors data into new clickhouse table
- [x] Add rendering code to dashboard main graph
- [ ] Add query to fetch a domain's imported visitors data in main graph's date range
- [ ] Hook up queried data to main graph
- [ ] Annotate graph/dashboard in some way to indicate imported data
- [ ] Add way to delete imported data
- [ ] Name imported data (may not be necessary if only one imported dataset per domain can exist at a time)*
- [ ] Checkboxes below

\* we also must consider CSV-imported data; data will be imported from multiple CSVs as it covers a number of tables, so having a representation of what is available and ability to delete individual components may be needed to avoid import of and simultaneous validation of a batch of CSVs.

### Tests
- [ ] Automated tests have been added

### Changelog
- [ ] Entry has been added to changelog

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated

2021-11-18 06:58 UTC, metmarkosaric commented
do we need to show that difference at all? 

we should not allow any imported data for the period after your Plausible stats have started tracking. 

the graph and presentation can stay the same for both first party and imported data. 

the best way to show that there's some imported data in any specific view would be to introduce a little "i" icon perhaps next to the download icon that tells something like "this date range includes some imported data". from here we can link to the docs that tells a bit more about the imported data and what it lacks compared to the first party data. this "i" only shows up in views that feature imported data and is not there otherwise. 

seems clean and minimal way of doing this. what do you think?

we just need to understand what the actual differences in usage there will be between first party and imported data. like for instance in the "month to date" view will people be able to click on a day that has imported data only like they can on a normal day that has Plausible data? if that feature is there, then at least for the top chart the third party data has a parity with the first party data so no real reason to visually differentiate between them

2021-11-18 10:49 UTC, m-col commented
> we should not allow any imported data for the period after your Plausible stats have started tracking.

Ah sorry I should clarified - currently data is only imported up to the date of the first plausible data point. For testing I have disabled that so I could visualise things better and that's what in the image. The red and blue lines will never overlap in time.

> the graph and presentation can stay the same for both first party and imported data.

Do you mean that they were form the same line (in the case of the visitors graph), and be counted together into the same counts in the other tables? I think this might work for some metrics (like the visitors graph) but others it might not make sense from a statistics point of view. However I can try to combine the stats for each panel as I'm adding it to the feature keeping this in mind and so for the time being we can assume they will be merged.


> seems clean and minimal way of doing this. what do you think?

Yeah that's nice!

> we just need to understand what the actual differences in usage there will be between first party and imported data. like for instance in the "month to date" view will people be able to click on a day that has imported data only like they can on a normal day that has Plausible data? if that feature is there, then at least for the top chart the third party data has a parity with the first party data so no real reason to visually differentiate between them

That would be ideal, and what I'm aiming for :)

2021-11-18 11:09 UTC, metmarkosaric commented
That's great! And yeah, we keep imported data consistent visually with the native data. No differences at all in the visual presentation (same line, color, font etc). Then we describe any possible drawbacks with the third party data in the docs. Say "third party data cannot be aggregated with native data when we do the calculation for visit duration" or whatever the drawbacks end up being in the final implementation.

2021-11-23 14:38 UTC, ACPK commented
@metmarkosaric @m-col - How does this work for events that are sent to GA (ex: "viewed product", "added product to shopping cart", "made purchase of multiple items")?

FYI - We've manually imported this historical data to Clickhouse via CSV imports.  One pain has been importing the event names to "goals" because the events are in Clickhouse and the goals table is in Postgres. As such, I've been exporting the goal list grouped by goal name to CSV and then importing the names of unique goal names to Postgres. My colleague asked why the goals table cannot show all "goals" directly from click house grouped by goal name.

2021-11-29 22:03 UTC, m-col commented
To update: the current state has all of the required data being imported from GA, and all of it is being merged into the plausible dashboard in the corresponding panel and tab. There are still a few issues that need ironing out. I've tried to keep the checkbox list on the first post up to date so they should be listed there. There are a few questions which would help to improve/fix the implementation.

Currently plausible distinguishes between 4 device types in the dashboard: desktop, laptop, tablet, mobile. Google Analytics uses 3: desktop, tablet and mobile. However I think the definitions the same: An extract from the Plausible docs ([link](https://plausible.io/docs/metrics-definitions#screen-size)):

> Shows the width of the screens used by your visitors. We measure the width of the browser window where your site is actually rendered rather than the full screen width. Anything under 576px screen size is considered a mobile device, up to 992px is considered a tablet, up to 1440px is considered a laptop and anything above 1440px is considered a desktop.

"Screen size" seems misleading here, because both the device screen resolution and the web page's viewport are valid and attainable metrics for a session, and "screen size" implies the former. GA exposes both [screen size](https://ga-dev-tools.web.app/dimensions-metrics-explorer/system/#screenResolution) and [browser size](https://ga-dev-tools.web.app/dimensions-metrics-explorer/platform-or-device#browserSize). The screen size thresholds that distinguish device types also seem odd. My low-end 5+ year old has a 1080x2160 screen size, and my laptop is 1920x1080. These would be considered a tablet and desktop according to plausible. It's possible that I've misunderstood how the calculations are done, or how the data is reported by the browser though! The relevance for this PR is that I'm wondering what the best way to get equivalent from GA. The options are the screen size or browser size, but also [device category](https://ga-dev-tools.web.app/dimensions-metrics-explorer/platform-or-device/#deviceCategory) directly. That latter one sounds like what the plausible "screen size" is meant to be so I wonder how they are deducing that informaiton.

Regarding locations: with regions and cities on the way, it might sense to also fetch these from GA at this point. They would likely have to be fetched by the time this PR is merged, even if cities and regions aren't yet tracked by plausible, as the import is a one-shot "get everything then you no longer need your google account" feature. Think I should work that into the clickhouse table now, and leave it out of the queries etc, or just leave it out altogether?

@ACPK The plans for our import are to consider each dimension individually, which makes import/export much easier, but that means that filtering and goals won't really be compatible. I tried importing everything into one table to enable this but the data can't be fetched all together from google (they limit what can be requested per query), leading to possibly duplicated visitor counts. Similarly data is exported spread across individual CSVs from Fathom (like Plausible) and this imported data also cannot be filtered.

2021-11-30 01:05 UTC, ACPK commented
@m-col Did you use Google Analytics 4? https://support.google.com/datastudio/answer/6370352?hl=en#zippy=%2Cin-this-article

2021-11-30 10:12 UTC, m-col commented
It's using Reporting API v4, which has equivalent methods and they have the same limits on dimensions etc. Is there an advantage to using Google Analytics Data API v1 (GA4) that I may have overlooked?

2021-11-30 11:05 UTC, ukutaht commented
### About devices

Yes I think your criticism of the screen size thing in Plausible is correct. We are planning to stop using the viewport size and instead infer the device type from the User-Agent in the future. I believe this is what GA's deviceCategory means as well. So I think we should import `deviceCategory` from GA.

We probably have to get rid of the 'laptop' category when we use the user-agent anyways, so it's OK if the import doesn't have any data for 'Laptop'.

### Locations

Yeah, since the import cannot be run again in the future, it's best to get all of the data in one go. It would be great if GA could export the same identifiers that we use - `ISO3166-2` for regions and `geoname_id` for city. I just checked and that does not seem to be the case..

@m-col how are you dealing with countries at the moment? Are we getting it as a name or as an identifier from GA? How is it merged with our own data?

2021-11-30 11:14 UTC, m-col commented
> @m-col how are you dealing with countries at the moment? Are we getting it as a name or as an identifier from GA? How is it merged with our own data?

Countries are being fetched as `countryIsoCode`: "Users' country's ISO code (in ISO-3166-1 alpha-2 format), derived from their IP addresses or Geographical IDs. For example, BR for Brazil, CA for Canada." [link](https://ga-dev-tools.web.app/dimensions-metrics-explorer/geo-network#countryIsoCode).

Regions can also be fetched in the format we want: "Users' region ISO code in ISO-3166-2 format, derived from their IP addresses or Geographical IDs." (`ga:regionIsoCode`).

City is less clear: we have `ga:cityId`: "Users' city ID, derived from their IP addresses or Geographical IDs. The city IDs are the same as the Criteria IDs found at https://developers.google.com/analytics/devguides/collection/protocol/v1/geoid." And also just the name `ga:city`: "Users' city, derived from their IP addresses or Geographical IDs.".

2021-11-30 12:00 UTC, ukutaht commented
That's great for countries and regions!

It does look like cities might be a pain. Let's see what we can do but even if they're missing from the import it's not a huge deal I think

2021-12-21 14:46 UTC, m-col commented
There are some updates I need to make in line with some of the new features, but in its current form it is working 100%!

I'm first going to rebase and make those updates but will then be focussing on getting tests written for all of the changes. Any review/comments on its current form would be appreciated!

2021-12-21 14:47 UTC, m-col commented
The import is not yet run in the background. It's convenient for development for it to be synchronous so I'm leaving that until the end.

2021-12-22 14:39 UTC, ukutaht commented
Sweet! Sounds good @m-col

2022-01-03 12:08 UTC, m-col commented
Quick update: the PR is rebased and updated such that utm_term and utm_content are imported and merged, as are regions. Cities are added to the imported_locations table but are not imported from GA. As discussed on matrix, this is due to the GA city data not being compatible with the city data used by plausible, and so the data cannot be merged. The field is kept in the table for future imports from other sources.

I am now continuing work on fixing current tests + adding new ones.

2022-01-04 11:20 UTC, ukutaht reviewed
Looks good overall.

I'm concerned about the big change from strings to atoms for _some_ metrics. The state it's currently in feels very error-prone. Maybe the right solution is to move completely to using atoms.

2022-01-04 11:20 UTC, ukutaht commented on lib/plausible/stats/breakdown.ex
> +    results = breakdown_sessions(site, query, property, metrics, pagination)
Is this so the `visits` metric doesn't leak when querying bounce rate and visit duration?

2022-01-04 11:20 UTC, ukutaht commented on lib/plausible_web/controllers/api/stats_controller.ex
> +        [:visitors, :pageviews, :bounce_rate, "time_on_page", :sample_percent]
Mixed list of atoms and strings

2022-01-04 16:43 UTC, m-col commented
I'm getting some incompatibilities with the countries and regions from data imported from GA, which allegedly follows the ISO standard. Still investigating whether the issue is with GA or `Location`. The patch to ensure the query doesn't fail is the commit https://github.com/plausible/analytics/pull/1466/commits/4f22c33b757b50822467ab24d5b49e27f3e33051

2022-01-04 16:48 UTC, m-col commented on lib/plausible/google/api.ex
> +    start_date = Date.add(end_date, -365)
No - we can set this to anything but it is required. Could bump it up to 20 years or so?

2022-01-04 16:52 UTC, m-col commented on lib/plausible/google/api.ex
> +          pageSize: 100_000
The API does support pagination, so we could fetch all data for the given time period and import that.

2022-01-04 16:55 UTC, m-col commented on lib/plausible/stats/base.ex
> +        {:is_not, value} ->
The imported data cannot be filtered, so in that case the imported tables are skipped over completely. The case statement is used for internal logic, such as ignoring empty values or `"Direct / None"`.

2022-01-05 10:57 UTC, m-col commented on lib/plausible/stats/base.ex
> +          |> where([i], i.region != "")
Hmm, not sure. The empty region is filtered from the dashboard but I suspect an internal `:is_not` filter is used (or should be).

2022-01-05 11:08 UTC, m-col commented on lib/plausible/stats/base.ex
> +        "visit:utm_content" ->
As-is it doesn't because the table is `imported_utm_content` without the trailing `"s"`. Happy to rename the table if that makes this more clear (and removes one clause).

2022-01-05 14:36 UTC, ukutaht commented
The ISO standard changes all the time. My local region had it's ISO code change as recently as 2019. Maybe we need some mappings from older to newer ones.

I like the patch, we had some cases on prod as well so this is useful.

2022-01-05 15:51 UTC, m-col commented
> I like the patch, we had some cases on prod as well so this is useful.

Happy to submit it as a standalone PR if you'd like it sooner.

2022-01-05 15:59 UTC, ACPK commented
@m-col Will importing CSVs be part of this PR or an additional PR?

2022-01-05 16:44 UTC, m-col commented on lib/plausible/stats/breakdown.ex
> +    results = breakdown_sessions(site, query, property, metrics, pagination)
Yep, exactly - we could just leave it in

2022-01-05 16:49 UTC, m-col commented on lib/plausible/google/api.ex
> +    start_date = Date.add(end_date, -365)
Looks like the earliest valid date is 2005-01-01 so we can use that to collect all data.

2022-01-06 11:07 UTC, m-col commented
> @m-col Will importing CSVs be part of this PR or an additional PR?

It won't be part of this PR. Importing via CSVs is something we have dicussed and are open to adding but there are no immediate plans to implement it.

2022-01-06 12:05 UTC, m-col commented on lib/plausible/imported/browsers.ex
> +    field :timestamp, :naive_datetime
Currently the imported data timeseries uses the same `select_merge` as the native timeseries code:
```elixir
            select_merge: %{
              "date" => fragment("toDate(toTimeZone(?, ?)) as date", e.timestamp, ^site.timezone)
            }
```
I've made changes such that imported data comes with date+hour, which is then converted to UTC (with any hours near 00:00 possibly causing date changes), and then just to `Date` for storage.

When when reading the data, such as in the snippet above, does the `site.timezone` need applying? In that case - the full datetime might be required (just with date+hour at least). Unless perhaps we convert to `site.timezone` upon import and save as that. This might cause problems if `site.timezone` is changed, though. What do you think? The timezone logic is quite confusing!

2022-01-06 12:46 UTC, ukutaht commented on lib/plausible/stats/breakdown.ex
> +    results = breakdown_sessions(site, query, property, metrics, pagination)
Hmm I like the way you suppress it. Otherwise someone could start depending on this undocumented return value and have the rug pulled from underneath them if we ever decide to remove this unnecessary field.

Maybe just add a comment that this is what it's doing? Took me a second to understand why it's needed

2022-01-06 12:51 UTC, ukutaht commented on lib/plausible/stats/base.ex
> +        "visit:utm_content" ->
Oh I see. I think it's worth making it consistent with other utm tables

2022-01-06 12:54 UTC, ukutaht commented on lib/plausible/google/api.ex
> +    start_date = Date.add(end_date, -365)
Sounds good to me 👍

2022-01-06 12:59 UTC, ukutaht commented on lib/plausible/google/api.ex
> +          pageSize: 100_000
OK, maybe not top priority but I'm sure it'll come up and needs to be fixed at some point

2022-01-06 15:32 UTC, ukutaht commented on lib/plausible/stats/base.ex
> +        {:is_not, value} ->
Fair enough, makes sense

2022-01-06 15:44 UTC, m-col commented on lib/plausible/stats/breakdown.ex
> +    results = breakdown_sessions(site, query, property, metrics, pagination)
I'm thinking actually if "visits" is the only thing that ever gets filtered, that can be explicitly checked rather than the approach taken here, to remove everything except the metrics and property. I'll try that - the tests should tell me if that approach doesn't work.

2022-01-07 17:45 UTC, m-col commented on lib/plausible/stats/base.ex
> +          |> where([i], i.region != "")
See https://github.com/plausible/analytics/pull/1466/commits/cfd27b2047a9fa523ddcf48618ab61d63b32fbff which addresses this. I think this is an improvement as it reduces some code duplication and makes internal filtering more consistent. However it does mean that the filtering is only applied to `StatsController` and not `ExternalStatsController`, which may not be desirable. Let me know if you think it would be better to always apply the filtering, as is currently the case.

2022-01-09 14:11 UTC, ukutaht commented on lib/plausible/imported/browsers.ex
> +    field :timestamp, :naive_datetime
The `toTimeZone` is needed for native data because we allow the user to change the timezone on the fly. You can switch the dashboard from one timezone to the other and have the changes reflected immediately.

So for native data, timestamps are stored in UTC and the timezone conversion is applied at query time.

This is different from Google Analytics where the timezone conversion is applied during data collection. They store timestamps in local time, not UTC. No conversion is applied when querying. This means if you change the timezone in GA, it won't apply to historical data, it changes how future data is collected.

Although it might sound like Plausible is better in this regard with more flexibility, we need to change to storing local timestamps as well. The flexibility prevents us from making a number of optimizations that Clickhouse and other OLAP databases provide (materialized views, for example). Changing timezones is very rare and the benefit of these optimizations outweighs the benefit of the flexibility in timezones.

With this in mind, we should not attempt to make the imported tables have the same flexible timezone feature as native data (for which storing full DateTimes would be necessary). I think we should query `ga:date` instead of `ga:dateHour` and store it as it comes with no timezone conversion as a `Date`. And when querying, we should ignore the timezone and just return data in whatever local timezone it's stored in.

2022-01-15 18:40 UTC, m-col commented
I'm seeing all region values fetched from GA being `(not set)`. This is the `ga:regionIsoCode` metric. Fetching `ga:regionId` (a non-standard ID like their city IDs) in the same request shows that most rows do in fact have non-null region value. This means that for whatever reason GA doesn't want to export ISO standard region data. I think it would be good to leave that metric in the request in case it changes in the future though; it doesn't really cost anything to include it.

2022-01-15 18:52 UTC, ukutaht commented
> 

That's disappointing but yeah, let's attempt to import in case it changes

2022-01-23 17:34 UTC, m-col commented
I've set up imports to run in the background, sending an email upon completion, for either success or fail. That completes the core code in `lib`, leaving just the tests, so perhaps now is a good time for a review while I write some tests.

2022-01-23 22:35 UTC, m-col commented
The last commit that I've just pushed is the very first that starts touching the tests. I'm pushing it to get advice, as I think I've overlooked some setup for using the database from inside tests. When running the test that the commit touches (which inserts some imported browser data), I get this error:
```
  1) test GET /api/stats/:domain/browsers returns top browsers including imported data (PlausibleWeb.Api.StatsController.BrowsersTest)
     test/plausible_web/controllers/api/stats_controller/browsers_test.exs:44
     ** (UndefinedFunctionError) function ClickhouseEcto.Connection.to_constraints/2 is undefined or private. Did you mean one of:
     
           * to_constraints/1
     
     code: populate_stats(site, [
     stacktrace:
       (clickhouse_ecto 0.2.8) ClickhouseEcto.Connection.to_constraints(%Clickhousex.Error{code: "16", constraint_violations: [], message: "Code: 16. DB::Exception: No such column bounces in table plausible_test.imported_browsers (db15ac1f-8aac-4857-9b15-ac1f8aac2857). (NO_SUCH_COLUMN_IN_TABLE) (version 21.11.4.14 (official build))\n"}, [source: "imported_browsers"])
       (ecto_sql 3.7.1) lib/ecto/adapters/sql.ex:817: Ecto.Adapters.SQL.struct/10
       (ecto 3.7.1) lib/ecto/repo/schema.ex:744: Ecto.Repo.Schema.apply/4
       (ecto 3.7.1) lib/ecto/repo/schema.ex:367: anonymous fn/15 in Ecto.Repo.Schema.do_insert/4
       (ecto 3.7.1) lib/ecto/repo/schema.ex:269: Ecto.Repo.Schema.insert!/4
       (elixir 1.12.1) lib/enum.ex:1553: Enum."-map/2-lists^map/1-0-"/2
       test/plausible_web/controllers/api/stats_controller/browsers_test.exs:45: (test)
```

The interesting part, `No such column bounces in table plausible_test.imported_browsers`, suggests that the imported table doesn't have a column, but both the schema and the migration that sets up the database do in fact have the `bounces` column. I've tried reseting everything with mix, but to no avail.

Can anyone spot anything wrong with how I'm creating the database/test environment or inserting the data?

2022-01-24 20:59 UTC, ukutaht commented
Have you changed your migrations since the last time you ran tests?

Your test DB will get into an inconsistent state if you do the following:
1. Create a migration
2. Run tests (which automatically runs migrations in the test database)
3. Change the migration (e.g. add `bounces` to the `imported_browsers` table)
4. Run tests again

Ecto is not smart enough to be able to _diff_ the migration with the actual schema and deal with it. As far as Ecto is concerned you ran the migration in Step 2 and it doesn't need to be run again. And thus the test database schema is different from the changes made in Step 3.

If this is the case, you can try
```bash
$ MIX_ENV=test mix ecto.reset
```

2022-01-24 21:14 UTC, m-col commented
Ah of course! I missed the `MIX_ENV=test` before resetting. Great, thanks, I'm past that step now and can start testing.

2022-01-29 19:43 UTC, m-col commented on lib/plausible/google/api.ex
> +          pageSize: 100_000
Done!

2022-01-29 19:48 UTC, m-col commented
Update: the PR is "finished"(/ready for review)! All of the review comments have been addressed now, and lots of tests have been added to test the GA import and API requests yielding mixed native/imported data. The tests should pass but the PR requires https://github.com/plausible/clickhouse_ecto/pull/1 so won't pass on GH until that is merged.

2022-01-31 16:25 UTC, ukutaht commented
Hey sorry will review this week

2022-02-01 17:10 UTC, ukutaht requested changes
Great work @m-col ❤️ I like that it's running in the background now.

Some specific comments below. One general request I would add is to add documentation for the feature, both for developers and for users. Cover things like:
1. Provided I have a GA account, how would I as a developer test this feature on my laptop?
2. For users, what caveats are there to importing. What can I expect to work, what won't work?
3. For users, any limits there are to importing (like the 100k row limit if we don't implement pagination yet)
4. For users, how the time range for import is determined.

2022-02-01 17:10 UTC, ukutaht commented on lib/plausible_web/controllers/api/stats_controller.ex
> +        if Map.get(params, "filters", "{}") != "{}" do
This line was a bit weird to read. How about `if Map.has_key?("filters") do`?

2022-02-07 20:05 UTC, m-col commented on lib/plausible_web/controllers/api/stats_controller.ex
> +        if Map.get(params, "filters", "{}") != "{}" do
Sometimes the key is there but the value is `"{}"` and that should also pass. But perhaps this is also better?:
```suggestion
        if not Map.has_key?("filters") or params["filters"] == "{}" do 
```

2022-02-07 22:08 UTC, ukutaht commented on lib/plausible_web/controllers/api/stats_controller.ex
> +        if Map.get(params, "filters", "{}") != "{}" do
Ah I see, this is the raw filters parameter.

The filters are parsed a few lines above using `Query.from(params)`. You could use the result from that on this line to make it cleaner:

```elixir
if Enum.any?(query.filters) do
   # ...
end
```

2022-02-07 23:14 UTC, m-col commented on lib/plausible_web/controllers/api/stats_controller.ex
> +        if Map.get(params, "filters", "{}") != "{}" do
Ah yes that's much better

2022-02-07 23:25 UTC, m-col commented on lib/plausible/google/api.ex
> +            |> Enum.map(&Task.await(&1, 120_000))
Interesting, makes sense. I wonder if it's necessary to parallelise this at all, given that it runs in the background and emails the user later - does it make much difference to them? On the backend-side, maybe there is an argument to be made about this being lower priority than serving the dashboard for example, and parallelising it might cause bandwidth spikes? What do you think?

2022-02-08 00:00 UTC, m-col commented on lib/workers/send_email_report.ex
> +        unique_visitors: curr_period[:visitors]["value"],
I haven't looked at this just yet, but the aim is to get everything as atoms as they atoms are needed for use in ecto subqueries, where strings can't be used. I agree this should be consistent everywhere - anywhere strings are still there is an oversight.

2022-02-08 15:13 UTC, ukutaht commented on lib/workers/send_email_report.ex
> +        unique_visitors: curr_period[:visitors]["value"],
OK. Do pick one style and make everything consistent in that direction.

Workarounds are possible for the 'strings in subquery' problem. I can help figure something out.

2022-02-08 23:54 UTC, m-col commented on lib/workers/send_email_report.ex
> +        unique_visitors: curr_period[:visitors]["value"],
Got it - everything should now be consistent across the board. Specifically, strings will only appear on the initial query side, and any data output from `Stats` uses atoms exclusively. (Not pushed yet)

2022-02-09 00:02 UTC, m-col commented on lib/plausible/imported/site.ex
> +  # TODO: utm_sources. Google reports sources and utm_sources unified.
I don't think so, but I'm going to take a closer look to be certain. GA don't make the distinction between `sources` and `utm_sources` that Plausible does, but does provide a way to identify which of their source entries were utm sources. I'll update you soon with further explanation - it might also be good for the docs as a caveat of the GA data.

2022-02-10 04:25 UTC, ukutaht commented
I like the way you've broken in down. Seems like the best we can do

2022-02-10 20:25 UTC, ukutaht commented on lib/plausible/stats/breakdown.ex
> +      |> transform_keys(%{custom_prop => String.to_atom(custom_prop)})
Atoms are not garbage collected. If you call `String.to_atom` on external input like this, it creates a memory leak. External inputs should always be kept as strings for this reason and not converted to Atoms.

2022-02-10 20:25 UTC, ukutaht commented on lib/plausible/stats/breakdown.ex
> +        |> String.to_atom()
Same comment about `String.to_atom`

2022-02-10 20:29 UTC, ukutaht commented on lib/plausible/stats/breakdown.ex
> +      |> transform_keys(%{custom_prop => String.to_atom(custom_prop)})
There is only one use of String.to_atom in our whole codebase at the moment and in that case there is a validation layer before to make sure it's only called on a limited list of strings that can be used for filtering.

The right thing would be to ban the use of `String.to_atom`. It is a dangerous and unsafe part of the Elixir language.

2022-02-10 22:18 UTC, m-col commented on lib/plausible/stats/breakdown.ex
> +      |> transform_keys(%{custom_prop => String.to_atom(custom_prop)})
Ah, I didn't consider that. I've pushed another commit that reverts those specific changes so they are kept as strings. This means that `breakdown` _can_ return strings but only if `"event:props:<prop>"` is queried. However the resulting key is converted to `:name` immediately: https://github.com/m-col/analytics/blob/import/lib/plausible_web/controllers/api/stats_controller.ex#L867.

It might be nicer to move that `transform_keys` to inside the `breakdown` definition for the `"event:props:"` match, which would keep the strings isolated to a smaller area (and would never be returned from `breakdown`). I can make that change too if you think it'd be good - I'm not sure if that would have any undesired side effects, such as if there might be a good use case for `breakdown` to actually return the `prop_name` as a key.

2022-02-12 12:48 UTC, m-col commented
Corresponding docs have been submitted here: https://github.com/plausible/docs/pull/183

2022-02-15 16:32 UTC, ukutaht commented on lib/plausible/stats/breakdown.ex
> +    # TODO: migrate schema field to 'os'
Missed TODO item here

2022-02-26 11:57 UTC, m-col commented
Rebased.

What kind of timeline do you envisage for merging this feature?

2022-02-28 21:14 UTC, ukutaht commented
Thanks @m-col. The plan is to integrate it this week and start testing with customers next week.

2022-03-10 21:34 UTC, ukutaht commented
Thanks for all the work @m-col. We'll do some internal testing tomorrow and real user testing next week.

2022-03-10 21:34 UTC, ukutaht commented
This was completed in #1753

2022-03-10 21:34 UTC, closed without merging