Add API to retrieve site by domain
plausible/analytics pull request #1942
Opened 2022-06-01 04:12 UTC by kurtmc

### Changes

Please describe the changes made in the pull request here.

Below you'll find a checklist. For each item on the list, check one option and delete the other.

### Tests
- [ ] Automated tests have been added
- [ ] This PR does not require tests

### Changelog
- [ ] Entry has been added to changelog
- [ ] This PR does not make a user-facing change

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated
- [ ] This change does not need a documentation update

### Dark mode
- [ ] The UI has been tested both in dark and light mode
- [ ] This PR does not change the UI

2022-06-02 08:51 UTC, ukutaht requested changes
Thanks for this, looks good to me!

The only change I would request is to open this endpoint up for `admin` level users as well.  Otherwise it's ready to merge.

2022-06-02 08:51 UTC, ukutaht commented on lib/plausible_web/controllers/api/external_sites_controller.ex
> +    site = Sites.get_for_user(conn.assigns[:current_user].id, site_id, [:owner])
Let's expand this to `[:owner, :admin]`. Most other endpoints in this controller allow both owners and admins.

2022-06-02 21:54 UTC, kurtmc commented
Thanks @ukutaht ! I've applied that change now.

2022-06-03 07:25 UTC, ukutaht approved these changes

2022-06-03 07:37 UTC, merged