add upper bound to limit parameter
plausible/analytics pull request #2226
Opened 2022-09-14 14:36 UTC by RobertJoonas

### Changes

Define an upper boundary for the `limit` parameter used in Stats API.

### Tests
- [x] Automated tests have been added

### Changelog
- [ ] Entry has been added to changelog

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated

### Dark mode
- [x] This PR does not change the UI

2022-09-14 15:00 UTC, RobertJoonas commented
Pinging @plausible/developers here for a discussion on what this limit should be set to.

I did some basic testing with Postman, running the following query

```
https://plausible.io/api/v1/stats/breakdown
	?site_id=plausible.io
	&period=custom
	&date=2019-01-22,2022-09-14
	&property=visit:referrer
	&metrics=visitors,pageviews,visit_duration,bounce_rate
	&limit=XXX
```
10 times, with `limit=100`, `limit=1000`, `limit=10000` and made sure that the response actually includes the limit number of results.

Here is how long the queries took to get the data, and the payload sizes:

### limit = 100
| average time | max time | min time | payload size |
|-|-|-|-|
| 811ms | 1439ms | 614ms | 11.2KB |

### limit = 1 000
| average time | max time | min time | payload size |
|-|-|-|-|
| 1215ms | 2800ms | 836ms | 106.4KB |

### limit = 10 000
| average time | max time | min time | payload size |
|-|-|-|-|
| 2222ms | 2900ms | 2050ms | 1.12MB |

2022-09-15 08:04 UTC, aerosol requested changes
Suggestion inline

2022-09-15 08:04 UTC, aerosol commented on lib/plausible_web/controllers/api/external_stats_controller.ex
> +    end
```suggestion
  with {limit, ""} when limit > 0 and limit <= @max_breakdown_limit <- Integer.parse(limit) do
    {:ok, limit}
  else _ -> 
    {:error, "Please provide limit as a number between 1 and #{@max_breakdown_limit}."}
  end
```

This way you're not crashing the request when someone sends `limit=foo`(the cases for non-integer and zero/negative limits could maybe use some tests too?)

2022-09-15 10:17 UTC, ukutaht commented
> Pinging @plausible/developers here for a discussion on what this limit should be set to.
> 
> I did some basic testing with Postman, running the following query
> 
> ```
> https://plausible.io/api/v1/stats/breakdown
> 	?site_id=plausible.io
> 	&period=custom
> 	&date=2019-01-22,2022-09-14
> 	&property=visit:referrer
> 	&metrics=visitors,pageviews,visit_duration,bounce_rate
> 	&limit=XXX
> ```
> 
> 10 times, with `limit=100`, `limit=1000`, `limit=10000` and made sure that the response actually includes the limit number of results.
> 
> Here is how long the queries took to get the data, and the payload sizes:
> 
> ### limit = 100
> average time	max time	min time	payload size
> 811ms	1439ms	614ms	11.2KB
> ### limit = 1 000
> average time	max time	min time	payload size
> 1215ms	2800ms	836ms	106.4KB
> ### limit = 10 000
> average time	max time	min time	payload size
> 2222ms	2900ms	2050ms	1.12MB

Not super scientific but hard to get any good data from the system given the current observability tools we have. I would say let's go with 1000 for now and increase it when we have better information and/or more capacity.

2022-09-15 10:25 UTC, RobertJoonas commented on test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
> -          "date" => "2021-01-01",
Reduce code lines - these can be defaults

2022-09-15 10:27 UTC, RobertJoonas commented on lib/plausible_web/controllers/api/external_stats_controller.ex
> +    end
Thanks, @aerosol! Changed it and added tests: https://github.com/plausible/analytics/pull/2226/commits/1e1a47092985e75b837c1d2547511e2ffe632d2d

2022-09-15 12:05 UTC, vinibrsl approved these changes

2022-09-15 19:44 UTC, aerosol approved these changes

2022-09-16 07:21 UTC, merged

2022-09-16 07:22 UTC, ukutaht commented
👍

Will deploy this early next week