improve first launch experience for self hosters
plausible/analytics pull request #2357
Opened 2022-10-19 11:26 UTC by ruslandoga

### Changes

This PR removes admin creds set in env vars and replaces them with web ui setup on first launch.

### Tests
- [x] Automated tests have been added

### Changelog
- [ ] Entry has been added to changelog

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated

### Dark mode
- [x] The UI has been tested both in dark and light mode

2022-10-19 11:27 UTC, ruslandoga commented on lib/plausible/application.ex
> +      Plausible.Release.set_first_launch()
- [ ] maybe do this after Plausible.Repo is started and before endpoint, this would solve a race-condition when `first_launch` in `nil`

2022-10-19 11:29 UTC, ruslandoga commented on lib/plausible_web/controllers/auth_controller.ex
> +        conn
when first_launch?, it still shows the registration forms, even with registration disabled, otherwise the user won't be able to get into the system

2022-10-19 11:29 UTC, ruslandoga commented on lib/plausible_web/controllers/auth_controller.ex
> +          if Release.first_launch?(), do: Release.set_first_launch(false)
once registered, first_launch? is set to false

- [ ] forgot to test that

2022-10-19 11:30 UTC, ruslandoga commented on test/plausible_web/controllers/admin_auth_controller_test.exs
>      test "logs admin user in automatically when authentication is disabled", %{conn: conn} do
not sure what to do about this test and `DISABLE_AUTH` in general

2022-10-19 11:30 UTC, ruslandoga commented on rel/overlays/init-admin.sh
> -"${BIN_DIR}"/bin/plausible eval Plausible.Release.init_admin
or should these be kept but made no-op?

2022-10-21 08:35 UTC, ruslandoga commented on test/plausible_web/controllers/admin_auth_controller_test.exs
>      test "logs admin user in automatically when authentication is disabled", %{conn: conn} do
I'm keeping it as before to avoid breaking anyones setup

2022-10-21 08:35 UTC, ruslandoga commented on rel/overlays/init-admin.sh
> -"${BIN_DIR}"/bin/plausible eval Plausible.Release.init_admin
I restored this script and everything else related to `init_admin`

2022-10-29 07:51 UTC, aerosol commented on lib/plausible/application.ex
> +      {Plausible.Release.BlockingChild, fn -> Plausible.Release.set_first_launch() end},
At this point you can already access application env so there's no point in running this code in a non-self-hosted setup -- you can dynamically generate the list of children started. Also the GenServer for this seems to be an overkill, a regular function should block it just fine, no? 
My concern is this is prone to race conditions, you have no guarantees the Repo is up by this point, I think it starts asynchronously?

2022-10-29 07:54 UTC, ruslandoga commented on lib/plausible/application.ex
> +      {Plausible.Release.BlockingChild, fn -> Plausible.Release.set_first_launch() end},
Where would the function call be placed?

2022-10-29 08:19 UTC, ruslandoga commented on lib/plausible/application.ex
> +      {Plausible.Release.BlockingChild, fn -> Plausible.Release.set_first_launch() end},
I've added one more commit, but I think generating the children dynamically it's a worse approach since it splits the logic and executes the setup code less often in tests.

2022-10-29 08:29 UTC, ruslandoga commented on lib/plausible/application.ex
> +       fn -> Plausible.Release.wait_for_repo(Plausible.Repo) end},
waiting for repo unconditionally as it is required for `Plausible.Session.Salts` as well

2022-10-29 08:34 UTC, aerosol commented on lib/plausible/application.ex
> +      {Plausible.Release.BlockingChild, fn -> Plausible.Release.set_first_launch() end},
Let me have a proper look on Monday and get back to you

2022-10-31 09:06 UTC, aerosol commented on lib/plausible_release.ex
> +    Application.fetch_env!(@app, :is_selfhost)
Do you know what is setting the env var for me?

```
$ SELFHOST=true iex -S mix
...
iex(1)> System.get_env "SELFHOST"
"false"
```

2022-10-31 10:49 UTC, ruslandoga commented on lib/plausible_release.ex
> +    Application.fetch_env!(@app, :is_selfhost)
Probably `config/.env.dev`

2022-10-31 12:57 UTC, aerosol commented on lib/plausible_release.ex
> +    Application.fetch_env!(@app, :is_selfhost)
sneaky, thanks :pray:

2022-11-01 13:53 UTC, aerosol requested changes
Some comments inline. 

In general I'd consider simplifying it further, without introducing that much application env fiddling -- so that the plug kicks in only in self-hosted environment and the first launch is determined by checking if any User exists, on each self-hosted browser request. This extra query in the `:browser` pipeline hurts no one I believe in terms of load/performance and gets us much better clarity.

2022-11-01 13:53 UTC, aerosol commented on test/plausible_web/controllers/auth_controller_test.exs
> +      on_exit(fn -> Application.put_all_env(plausible: prev_env) end)
we have now helpers to do that: https://github.com/ruslandoga/analytics/blob/first-launch/test/support/test_utils.ex#L12-L31

2022-11-01 13:53 UTC, aerosol commented on test/plausible_web/controllers/auth_controller_test.exs
> +      true = Release.first_launch?()
```suggestion
      assert Release.first_launch?()
```

2022-11-01 13:53 UTC, aerosol commented on test/plausible_web/controllers/auth_controller_test.exs
> +      assert Release.first_launch?() == false
```suggestion
      refute Release.should_be_first_launch?()
      refute Release.first_launch?()
```

2022-11-01 13:53 UTC, aerosol commented on lib/plausible/application.ex
> +      maybe_set_first_launch(),
Those two blocking children are in conflict now, you need IDs to run them. However as mentioned elsewhere, you don't need a GenServer that shuts down immediately for this, child specs can be built like this:

```elixir 
%{id: Ignored.WaitForRepo, start: {__MODULE__, :wait_for_repo, []}} # returns :ignore,
%{id: Ignored.MaybeSetFirstLaunch, start: {Release, :maybe_set_first_launch, []} # returns :ignore
```
Everything happens in the application startup process and children are started sequentially. Since you wait for the Repo anyway, there's no need for any wrappers. At the end `Enum.reject` all that returned `:ignore`.

2022-11-01 13:53 UTC, aerosol commented on lib/plausible_web/controllers/auth_controller.ex
> +          case user.email_verified do
`if`?

2022-11-01 13:53 UTC, aerosol commented on lib/plausible/application.ex
> +    alias Plausible.Release
let's keep aliases at the top

2022-11-01 13:56 UTC, ruslandoga commented on test/plausible_web/controllers/auth_controller_test.exs
> +      on_exit(fn -> Application.put_all_env(plausible: prev_env) end)
I don't think those helpers would work here since I'm reseting all plausible env to prev values after the test has run. There are several keys that are changed.

2022-11-01 13:56 UTC, ruslandoga commented on test/plausible_web/controllers/auth_controller_test.exs
> +      true = Release.first_launch?()
That's not really the assertion of this test case.

2022-11-01 13:57 UTC, ruslandoga commented on test/plausible_web/controllers/auth_controller_test.exs
> +      assert Release.first_launch?() == false
`refute` passes on `nil`. I want to ensure the value returned is `false`. I can assert on `is_boolean` though.

2022-11-01 13:58 UTC, aerosol commented on test/plausible_web/controllers/auth_controller_test.exs
> +      on_exit(fn -> Application.put_all_env(plausible: prev_env) end)
Sure ok, see my final comment about not using that many application env conditionals, perhaps it'd help. That comes with an extra bonus of not having to wait for the repo ;)

2022-11-01 13:58 UTC, aerosol commented on test/plausible_web/controllers/auth_controller_test.exs
> +      true = Release.first_launch?()
still crashes on match error though :shrug:

2022-11-01 14:00 UTC, ruslandoga commented on lib/plausible_web/controllers/auth_controller.ex
> +          case user.email_verified do
I'd like to keep the changes only relevant to the PR :)

2022-11-01 14:02 UTC, ruslandoga commented
> In general I'd consider simplifying it further, without introducing that much application env fiddling -- so that the plug kicks in only in self-hosted environment and the first launch is determined by checking if any User exists, on each self-hosted browser request.

Right, I'll update the PR.

2022-11-01 14:04 UTC, ruslandoga commented on test/plausible_web/controllers/auth_controller_test.exs
> +      true = Release.first_launch?()
I don't think it's a problem that it can crash since code in `setup` blocks can also crash. But I'll update the PR.

2022-11-01 14:04 UTC, ruslandoga commented on test/plausible_web/controllers/auth_controller_test.exs
> +      on_exit(fn -> Application.put_all_env(plausible: prev_env) end)
We'd still need to wait for the repo for Salts genserver.

2022-11-01 14:17 UTC, ruslandoga commented on test/plausible_web/plugs/first_launch_plug_test.exs
> +  setup do
does `patch_env` handle multiple invocations for the same key?

2022-11-01 14:44 UTC, ruslandoga commented on test/plausible_web/controllers/admin_auth_controller_test.exs
> +      set_config(disable_registration: true)
I updated that function to use `patch_env` underneath. It has more logic that is handled by `patch_env` right now.

2022-11-02 10:52 UTC, aerosol commented on lib/plausible_web/controllers/auth_controller.ex
> +    assign(conn, :is_selfhost, Plausible.Release.is_selfhost())
What is the purpose of the assign in contrast to fetching from env each time?

2022-11-02 10:52 UTC, aerosol commented on lib/plausible_web/controllers/auth_controller.ex
> +    assign(conn, :is_selfhost, Plausible.Release.is_selfhost())
Ah I see it now, templates

2022-11-02 10:52 UTC, ruslandoga commented on lib/plausible_web/controllers/auth_controller.ex
> +    assign(conn, :is_selfhost, Plausible.Release.is_selfhost())
pure view functions and all that

2022-11-02 10:54 UTC, ruslandoga commented on lib/plausible_web/controllers/auth_controller.ex
> +    assign(conn, :is_selfhost, Plausible.Release.is_selfhost())
I can remove it and use app env in templates. That would be in line with the conventions of this project, I think.

2022-11-02 10:55 UTC, ruslandoga commented on lib/plausible_web/templates/auth/register_form.html.eex
> +    <% end %>
I'm using invitation template wording here ...

2022-11-02 10:55 UTC, ruslandoga commented on lib/plausible_web/templates/auth/register_form.html.eex
> +        end
... and here

2022-11-02 10:56 UTC, ruslandoga commented on lib/plausible_web/templates/auth/register_form.html.eex
> +    <%= if assigns[:is_selfhost] do %>
I'm using `assigns[:is_selfhost]` to avoid possible problems when this template is rendered outside of auth controller. I checked the project and it doesn't seem there are any places that do this, but still, better be safe :)

2022-11-02 10:58 UTC, ruslandoga commented on lib/plausible_release.ex
> +    is_selfhost() and not (_has_users? = Repo.exists?(Plausible.Auth.User))
I moved repo call after `and` to avoid calling it in the cloud edition.

2022-11-02 11:00 UTC, ruslandoga commented on CHANGELOG.md
> +- Allow self-hosted users to register via Web UI
not sure if it's descriptive enough. Maybe "Allow first time users to register via Web UI in self-hosted version"

2022-11-02 11:01 UTC, aerosol commented on lib/plausible_web/templates/auth/register_form.html.eex
> +    <%= if assigns[:is_selfhost] do %>
It's safe to use @is_selfhost and then crash loud if it's missing. IMHO tests should be responsible for ensuring it's there.

2022-11-02 11:04 UTC, aerosol commented on CHANGELOG.md
> +- Allow self-hosted users to register via Web UI
"Allow self-hosters to register an account on first launch"?

2022-11-02 11:20 UTC, aerosol approved these changes

2022-11-08 12:58 UTC, ukutaht approved these changes

2022-11-08 13:47 UTC, ruslandoga commented on lib/plausible_web/controllers/page_controller.ex
> +      |> halt()
```elixir
conn
|> put_session(:login_dest, conn.request_path)
|> redirect(to: "/login")
|> halt()
```

is copied from https://github.com/plausible/analytics/blob/101e5a68b5ff907978f1f7b220b17d2cf53da4b6/lib/plausible_web/plugs/auto_auth_plug.ex#L19-L22

2022-11-08 13:47 UTC, ruslandoga commented on lib/plausible_web/controllers/page_controller.ex
> -  plug PlausibleWeb.AutoAuthPlug
which used to be "invoked" here

2022-11-08 13:48 UTC, ruslandoga commented on lib/plausible_web/controllers/page_controller.ex
> -      render(conn, "index.html")
I'm removing `render` since it wasn't called due to `halt` in `AutoAuthPlug` anyway.

2022-11-08 13:57 UTC, ruslandoga commented on lib/plausible_web/controllers/page_controller.ex
> -      render(conn, "index.html")
actually, to keep the previous auto auth plug behaviour, we need to redirect all requests to `/login` from this controller action, regardless of whether the user is signed in.

2022-11-08 14:10 UTC, ruslandoga commented on lib/plausible_release.ex
> +  def selfhost? do
credo made me do it

2022-11-08 14:12 UTC, ruslandoga commented
@ukutaht that should be fixed in https://github.com/plausible/analytics/pull/2357/commits/923682080d5cd6efbaf054c0f2f9799db3cea759

2022-11-09 09:24 UTC, ukutaht commented on lib/plausible_web/controllers/page_controller.ex
```suggestion
@doc """
The root path is never accessible in Plausible.Cloud because it is handled by the upstream reverse proxy.

This controller action is only ever triggered in self-hosted Plausible. It redirects the user to /login where `PlausibleWeb.RequireLoggedOutPlug` plug kicks in. If they are already logged in, they are redirected to /sites, otherwise they'll see the /login page.
"""
```

2022-11-09 09:25 UTC, ukutaht commented on lib/plausible_web/controllers/page_controller.ex
I think a nice TODO for v1.6.0 would be to create a nice splash page that welcomes the user to their self-hosted Plausible installation and links to the /register and /login pages.

2022-11-10 11:42 UTC, aerosol approved these changes

2022-11-10 11:42 UTC, merged

2023-03-04 17:06 UTC, StreetStrider commented
I'm a self-hoster and I'm looking for a way to automatically setup admin user and some seeded data during plausible setup in our infra. The setup is (ofc) automatic.
I don't get the ratio behind this change, at some angle it looked like it's removing the ability to create admin user via scripting.
I'm struggling to understand, can someone help me with how do I setup admin user (and possible seed some data) during plain shell script or while docker image baking in Dockerfile?

2023-03-04 17:09 UTC, ruslandoga commented
👋 @StreetStrider 

https://github.com/plausible/analytics/discussions/2460#discussioncomment-4318576 might be helpful.

2023-03-04 19:12 UTC, StreetStrider commented
@ruslandoga I was able to populate `/app/lib/plausible-0.0.1/priv/repo/seeds.exs` with some debug code (like IO.puts) and run it via `/app/bin/plausible eval "Plausible.Release.seed()"`. I was able to actually run this code.

However, when I put an actual migration code ([like this one](https://github.com/ruslandoga/plausible-seeds-ci/blob/d650b951eed6ae3ec6d056ee0d588d7bf781e6a5/ci/seeds.exs)) in it, I got an error related to environment:
```
#0 0.518 ERROR! Config provider Config.Reader failed with:                                                                                                                                                         
#0 0.519 ** (RuntimeError) BASE_URL configuration option is required. See https://plausible.io/docs/self-hosting-configuration#server 
#0 0.519     (stdlib 3.17.1) erl_eval.erl:685: :erl_eval.do_apply/6                                                                                                                                                
#0 0.519     (elixir 1.13.4) src/elixir.erl:296: :elixir.recur_eval/3                                                                                                                                              
#0 0.519     (elixir 1.13.4) src/elixir.erl:274: :elixir.eval_forms/3
…
```
I've double-checked that process environment is correctly propagated, however, it seemes that runner requires some additional step to pass env to it. I don't know how to fix this, this looks like a plausible/elixir specific issue.

2023-03-05 01:18 UTC, ruslandoga commented
Can you please share `plausible-conf.env`, `seeds.exs`, and `docker-compose.yml`?

2023-03-05 15:56 UTC, StreetStrider commented
@ruslandoga 
```yaml
  plausible:
    # image: plausible/analytics:latest
    build:
      context: .
    # restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
    #  - mail
    # ports:
    #   - 8083:8000
    environment:
      SECRET_KEY_BASE: ${SECRET_KEY_BASE:?err}
      BASE_URL: ${BASE_URL:?err}
      # ADMIN_USER_EMAIL: ${ADMIN_USER_EMAIL:?err}
      # ADMIN_USER_NAME: ${ADMIN_USER_NAME:?err}
      # ADMIN_USER_PWD: ${ADMIN_USER_PWD:?err}
```
We retrieve env from dotenv provided by compose. I've commented out `image` to be able to replace it with Dockerfile instead, to run seed. Dockerfile is simple at the moment:
```Dockerfile
FROM plausible/analytics:latest

COPY seed.exs lib/plausible-0.0.1/priv/repo/seeds.exs
```

```
alias Plausible.Repo
alias Plausible.Auth.{User, Password}

_user =
  Repo.insert!(%User{
    name: "A B",
    email: "a@b.com",
    password_hash: Password.hash("abc"),
    email_verified: true
  })
```
I don't get on what stage should I run migrations. The seed is not running automatically.

2023-03-05 16:53 UTC, StreetStrider commented
It seemes that most convenient way is to put `/app/bin/plausible eval "Plausible.Release.seed()"` into compose's `command` before run, but it would be executed every time. I'm not sure is it idempotent as migrate command or not. If not, it would create seed's dups on every start.

2023-03-05 17:33 UTC, ruslandoga commented
I think the easiest way is to mount the seeds script as a volume and run it in `command`. I can help you make it idempotent.

2023-03-05 17:37 UTC, StreetStrider commented
@ruslandoga okay, I will continue investigating. Thank you for help.

2023-03-06 15:11 UTC, StreetStrider commented
For the record, I ended up using `COPY seed` + `command: eval Plausible.Release.seed` as above. The seed script got guard condition to determine db is empty, something like:
```exs
unless Repo.one(from(User)) do
  # run seed code
end
```

2023-03-08 20:56 UTC, ErikHumphrey commented
@StreetStrider Are you using anything to automatically sign in as the admin user? This seems to remove that as well for people that used an OAuth2 proxy, Keycloak, etc. to sign into a single user. Since sites aren't shared across users, you can't really use this in an organization anymore, right?

2023-03-09 00:46 UTC, StreetStrider commented
@ErikHumphrey we do not sign in automatically, that's still too much tech for us. We use the same secret storage to deploy and to login, but login is manual. The password is plain in our case.

2023-03-09 14:40 UTC, StreetStrider commented
@ErikHumphrey if you was referring to `sites` in plausible, then you can actually add any memberships. My seed script adds single member to single site, but it is flexible as any plain script, so you can create multiple sites and memberships.
```exs
	Repo.insert!(%Membership {
		site: site, # ref to previously created site
		user: owner, # ref to previously created admin user
		role: :owner,
	})
```

2024-08-06 21:20 UTC, tintin10q commented
This is so inconvenient. How does this make the first launch experience better for self hosters at all? You could have just kept the `ADMIN_USER_PWD` environments vars working. Also it is not stated anywhere really that these env vars got removed so I spend quite some time trying to plausible work, automatically registering the user but it was never going to work. 

Very bad change in my opinion. It is so much more complicated while it was working fine. You could have just also kept the env vars.

2026-06-01 18:03 UTC, nh2 commented
Yeah, this bit me too. Easy automated CI deployment now no longer works. I'll try to use a workaround as described above, but it is not nice that one now needs to deal with internals instead of having an official automatic way to auto-deploy.

In NixOS this allowed an automatic fully-declarative deploy approach; unfortunately due to this change, that had to get removed in https://github.com/NixOS/nixpkgs/pull/356221