Correct the spelling of JavaScript
plausible/analytics pull request #2380
Opened 2022-10-25 18:39 UTC by metmarkosaric

One person reported that we are spelling JavaScript without capital J and S so I thought I'd fix that and other places where we don't capitalize it correctly.

2022-10-25 19:32 UTC, vinibrsl approved these changes

2022-10-26 05:48 UTC, aerosol requested changes
@metmarkosaric there's a test at `/test/plausible_web/controllers/site_controller_test.exs:277` that needs a fix up now

2022-10-26 06:03 UTC, metmarkosaric commented
thanks @aerosol! i think i've done it now

2022-10-26 06:34 UTC, aerosol approved these changes

2022-10-26 06:34 UTC, merged