improve transfer ownership error message
plausible/analytics pull request #2651
Opened 2023-02-07 08:18 UTC by ruslandoga

### Changes

Possible fix for https://github.com/plausible/analytics/issues/2640

### Tests
- [x] Automated tests have been added

### Changelog
- [ ] Entry has been added to changelog

### Documentation
- [x] This change does not need a documentation update

### Dark mode
- [ ] The UI has been tested both in dark and light mode

2023-02-07 08:28 UTC, aerosol commented on lib/plausible_web/controllers/site/membership_controller.ex
> +              "#{email} has already been invited but hasn't yet accepted the join request to #{site_domain}"
Can we make this part of the constraint error message and traverse errors in an uniform way so that any extra messages we add in the future don't fall into the mysterious "transfer has failed" bucket?

2023-02-07 08:30 UTC, ruslandoga commented on lib/plausible_web/controllers/site/membership_controller.ex
> +              "#{email} has already been invited but hasn't yet accepted the join request to #{site_domain}"
Sure. Should it be part of this PR? Re: implementation.

2023-02-07 08:31 UTC, aerosol commented on lib/plausible_web/controllers/site/membership_controller.ex
> +              "#{email} has already been invited but hasn't yet accepted the join request to #{site_domain}"
Your call 🤗

2023-02-07 08:31 UTC, aerosol approved these changes

2023-02-07 08:33 UTC, ruslandoga commented on lib/plausible_web/controllers/site/membership_controller.ex
> +              "#{email} has already been invited but hasn't yet accepted the join request to #{site_domain}"
Otherwise it'd be hard to distinguish between a double invite and invite -> transwer ownership. I can also use `invitation.role == :owner` but it seems a bit more error prone.

2023-02-07 08:34 UTC, ruslandoga commented on lib/plausible_web/controllers/site/membership_controller.ex
> +              "#{email} has already been invited but hasn't yet accepted the join request to #{site_domain}"
Or maybe just returning `already invited` for all errors is fine? I also noticed that the flash message disappears very quickly, not enough time to read it if it's long.

2023-02-07 08:36 UTC, aerosol commented on lib/plausible_web/controllers/site/membership_controller.ex
> +              "#{email} has already been invited but hasn't yet accepted the join request to #{site_domain}"
Yes, I think that's fine. It's clear enough to let the user know it's an existing invitation preventing proceeding. Re: flash message - I think we can double the timeout there: https://github.com/ruslandoga/analytics/blob/master/lib/plausible_web/templates/layout/_flash.html.eex#L37

2023-02-07 08:49 UTC, ruslandoga commented on lib/plausible_web/controllers/site/membership_controller.ex
> +              _other -> "Site transfer request to #{email} has failed"
I'm avoiding returning any other errors since I'm not sure if it's safe...

2023-02-07 08:50 UTC, ruslandoga commented on test/plausible_web/controllers/site/membership_controller_test.exs
> +      assert html_response(conn, 200) =~ "Already sent"
Not sure if that error is descriptive enough, though.

2023-02-07 09:20 UTC, ruslandoga commented on lib/plausible_web/controllers/site/membership_controller.ex
> +              "#{email} has already been invited but hasn't yet accepted the join request to #{site_domain}"
Re: flash https://github.com/plausible/analytics/pull/2652

2023-02-07 09:32 UTC, ruslandoga commented on lib/plausible_web/controllers/site/membership_controller.ex
> +              %{invitation: [error | _]} -> String.capitalize(error)
`:invitation` is not a schema field, but a custom error key.

```elixir
  |> unique_constraint([:email, :site_id],
      name: :invitations_site_id_email_index,
      error_key: :invitation,
      message: "invitation already exists"
    )
```

Should we still concat the other possible errors?

2023-02-07 11:58 UTC, aerosol commented on lib/plausible_web/controllers/site/membership_controller.ex
> +              %{invitation: [error | _]} -> String.capitalize(error)
Just the first one is fine. If anything confusing comes up we can address on case by case basis?

2023-02-09 13:14 UTC, aerosol approved these changes

2023-02-12 17:07 UTC, aerosol requested changes
Tests fail. Please don't force push with ongoing review, it makes it more difficult to track changes. Thx.

2023-02-12 17:12 UTC, ruslandoga commented
Sorry, my bad.

2023-02-13 04:43 UTC, ruslandoga commented on lib/plausible_web/controllers/site/membership_controller.ex
> +              %{invitation: ["already sent" | _]} -> "Invitation has already been sent"
I decided to reuse the approach used for duplicate invitations: https://github.com/plausible/analytics/blob/1d1ec9a673ecfa2857b8d43de1d09c7bef440a1a/lib/plausible_web/controllers/site/membership_controller.ex#L84-L85

2023-02-13 14:25 UTC, aerosol approved these changes

2023-02-13 14:25 UTC, merged