Visits metric
plausible/analytics pull request #2662
Opened 2023-02-09 14:04 UTC by RobertJoonas

### Changes

This PR is the foundation for displaying additional Top Stat metrics on the dashboard. It replaces the manual (absolute) CSS positioning with relative positioning, which significantly simplifies writing code for a varying number of Top Stat metrics.

### Tests
- [x] This PR does not require tests

### Changelog
- [x] This PR does not make a user-facing change

### Documentation
- [x] This change does not need a documentation update

### Dark mode
- [x] This PR does not change the UI

2023-02-09 14:10 UTC, RobertJoonas commented on assets/js/dashboard/stats/graph/visitor-graph.js
> +function renderLoader() {
This will render a loader icon exactly in the middle of a `position: relative` parent element. The function is called in two places because we want it to have a different parent in order to be placed correctly.

2023-02-09 14:53 UTC, ukutaht approved these changes
Looks good to me, I like getting rid of that crazy padding stuff that was used before.

Not relevant for this PR but this review made me think that maybe it's appropriate for the frontend to have some more knowledge. Currently it's the backend that decides which values to show in the top stats container. But what if the frontend made that decision and requested the appropriate top stats from the backend itself?

It may simplify parts of the code. The frontend would always know which top stats it will be showing. This would allow us to always have the correct container height during loading. I think it would also allow us to remove the `resetMetric` callback. Thoughts @RobertJoonas @vinibrsl?

2023-02-09 15:42 UTC, RobertJoonas commented
@ukutaht good idea! It would totally make sense if the `TopStats` component itself would be responsible for fetching the metrics allowed. It could also define which metrics can and cannot be selected. Basically, we could move the whole metric selection logic to `TopStats` (it won't have to share the state with the graph anymore, since it's only in localStorage now).

But probably still a good idea to merge this one as it is now, and do these changes in another PR, right?

2023-02-09 16:02 UTC, ukutaht commented
> But probably still a good idea to merge this one as it is now, and do these changes in another PR, right?

Yes, I think it's completely independent from any other work. Moving the logic is quite difficult and there may be some roadblocks along the way that we haven't thought about. Go ahead and continue with the current batch of work. Once the new metrics are added, we can have an experimental pairing session on refactoring the top stats logic :)

2023-02-09 18:12 UTC, vinibrsl requested changes

2023-02-09 18:12 UTC, vinibrsl commented on assets/js/dashboard/stats/graph/visitor-graph.js
> +              <canvas id="main-graph-canvas" className={'mt-4 select-none ' + extraClass}></canvas>
Not strictly related to the graph positioning, but what do you think of renaming `extraClass`? As I understand this variable styles the cursor when hovering the graph to make clear it's clickable. The only exception is when interval is hourly as the graph is not clickable when viewing this interval.

I suggest using `classNames` [(example here)](https://github.com/plausible/analytics/blob/3b73836136a1816f2c9847969e966e055cf142f7/assets/js/dashboard/stats/graph/top-stats.js#L80) or renaming this variable to be more descriptive, for example `clickableCursorUnlessHourly`.

2023-02-09 18:12 UTC, vinibrsl commented on assets/js/dashboard/stats/graph/visitor-graph.js
> +    const onlyGraphLoading = (mainGraphLoadingState === LoadingState.refreshing)
I did not understand this change. Could you please elaborate on it?

This variable confused me a bit. `onlyGraphLoading` would suggest the state is `loading` but it's `refreshing`.

2023-02-09 18:12 UTC, vinibrsl commented on assets/js/dashboard/stats/graph/visitor-graph.js
> +          {showLoader && !mainGraphRefreshing && renderLoader()}
I suggest adding this new condition to the `showLoader` variable instead of comparing it inside JSX. Also, it seems to me this new condition (`!mainGraphRefreshing`) negates the `showLoader` condition. It needs testing, but I think this would suffice:

```
const showLoader = LoadingState.isLoading(mainGraphLoadingState) || LoadingState.isLoadingOrRefreshing(topStatsLoadingState)
```

2023-02-13 15:47 UTC, RobertJoonas commented on assets/js/dashboard/stats/graph/visitor-graph.js
> +              <canvas id="main-graph-canvas" className={'mt-4 select-none ' + extraClass}></canvas>
Nice catch! Done in https://github.com/plausible/analytics/pull/2662/commits/fc9031b6fbcc2b9db72c8721fead277fc838761a. I also added the condition for a `minute` intercval which should not render clickable graph as well.

2023-02-13 15:51 UTC, RobertJoonas commented on assets/js/dashboard/stats/graph/visitor-graph.js
> +    const onlyGraphLoading = (mainGraphLoadingState === LoadingState.refreshing)
Yeah, I agree that it is a bit confusing. Basically, the `refreshing` state describes the situation where only the graph is loading, but Top Stats are not changing. This happens when `interval` or `metric` is changed.

I thought this variable name would better describe what is actually happening. I don’t like the word “refreshing”, as the only meaning of that state is that new data for **only the graph** is being fetched. “Refreshing” isn’t telling us that.

I’ve tried getting rid of the third state and only keep “loading vs loaded”, but couldn’t find an easy solution with sensible time. I think let’s come back to it later, perhaps when moving the top stat metric querying logic to frontend.

For now, I just reverted the variable name to what it was before - `mainGraphRefreshing`. I agree that mixing the meaning of `loading` vs `refreshing` causes even more confusion.

Also, as topStatsLoadingState should never become `refreshing`, I changed the two checks for that condition.

https://github.com/plausible/analytics/pull/2662/commits/0704e5e909b06c87be4e2a719be49e8587639378

2023-02-13 15:56 UTC, RobertJoonas commented on assets/js/dashboard/stats/graph/visitor-graph.js
> +          {showLoader && !mainGraphRefreshing && renderLoader()}
Good point! It doesn't actually negate it since the `showLoader` is an OR condition. But I was able to make it look better here: https://github.com/plausible/analytics/pull/2662/commits/6bca0d951e3a8bf76b9ffa4a92d4fb219d333a39

2023-02-14 12:59 UTC, vinibrsl approved these changes

2023-02-14 12:59 UTC, merged