Added IPv6 Finch support (via the environment-variable FINCH_IPV6)
plausible/analytics pull request #2737
Opened 2023-03-09 06:39 UTC by DKPillo

### Background

We are working with [Hetzner Cloud](https://www.hetzner.com/cloud) and have a setup, where only the proxy server is available via IPv4. The Docker hosts used to run services like plausible are attached to the network via IPv6.

Now we run unto the problem that plausible was not able to connect to Google API to connect with Analytics/Search Console.

After some research I found the following issue on finch: [IPv6 Documentation](https://github.com/sneako/finch/issues/163)

### Changes

Updates `lib/plausible/application.ex` and enables IPv6 support for Finch by setting `transport_opts: [inet6: true]` when environment variable `FINCH_IPV6` is set.

### Tests
- [X] This PR does not require tests

### Changelog
- [X] Entry has been added to changelog

### Documentation
- [X] [Docs](https://github.com/plausible/docs) have been updated

### Dark mode
- [X] This PR does not change the UI

2023-03-09 06:44 UTC, DKPillo commented
Merge Request for [Docs](https://github.com/plausible/docs/pull/365)

2023-03-20 10:18 UTC, aerosol approved these changes
Hey @DKPillo, looks good.

2023-03-20 11:30 UTC, ruslandoga commented on lib/plausible/application.ex
> +      maybe_ipv6 = if System.get_env("FINCH_IPV6"), do: [timeout: 15_000, inet6: true], else: [timeout: 15_000]
It doesn't seem like there are any other `System` calls in this module. Maybe, to keep this style going, we could move `System.get_env("FINCH_IPV6")` to `config/runtime.exs` and do an `Application.get_env` call here instead?

2023-03-20 11:31 UTC, aerosol commented on lib/plausible/application.ex
> +      maybe_ipv6 = if System.get_env("FINCH_IPV6"), do: [timeout: 15_000, inet6: true], else: [timeout: 15_000]
:facepalm: good call @ruslandoga, 100%

2023-03-20 11:32 UTC, aerosol requested changes
https://github.com/plausible/analytics/pull/2737#discussion_r1141980454

2023-03-22 19:09 UTC, DKPillo commented
Hi @aerosol, @ruslandoga 

Thank you, for your feedback.
I have updated the code so that `plausible/application.ex` uses `Application.get_env` to load the transport_opts for finch.

Unfortunately it does not work as intended and I have some debugging to do.
I will update the thread as soon as I have a working solution again.

2023-03-23 08:34 UTC, aerosol commented
Hey @DKPillo,

Thanks for coming back to us on this.

> Unfortunately it does not work as intended and I have some debugging to do.

Could you elaborate a bit on what doesn't work exactly?

2023-07-11 12:09 UTC, aerosol commented
hi @DKPillo, just checking if you still need this or if you encounter any problems. Otherwise I'm going to close the issue.

2023-07-29 09:53 UTC, DKPillo commented
Hi @aerosol sorry for the bad response time. I did not find enough time besides work to fix this issue as I wanted to.

I ended up fixing my problem by configuring a NAT to allow the server to access resources via IPv4 network.

2023-07-29 09:53 UTC, closed without merging