Fix date picker shifting day bug
plausible/analytics pull request #2848
Opened 2023-04-13 14:36 UTC by vinibrsl

This commit fixes a bug where picking a specific date in custom range takes you to the stats of the day before.

This was caused because Flatpickr returns a Date instance, and we were trying to parse this Date instance into day.js using the `utc` function, assuming it was a ISO-8601 string.

This commit fixes it by casting Date into dayjs using the `dayjs` function instead of `utc`.

2023-04-24 09:17 UTC, aerosol commented on assets/js/dashboard/datepicker.js
> +            onClose={setCustomDate}
what's the reason behind changing the event here?

2023-04-24 09:27 UTC, aerosol approved these changes

2023-04-24 13:46 UTC, ukutaht requested changes

2023-04-24 13:46 UTC, ukutaht commented on assets/js/dashboard/comparison-input.js
> +import dayjs from 'dayjs'
I think it's best to hide the `dayjs` usage and always access it through `./util/date`. In `util/date` we use it in UTC mode and I think it would be quite confusing to not use it in utc mode elsewhere.

2023-04-25 09:45 UTC, vinibrsl commented on assets/js/dashboard/comparison-input.js
> +import dayjs from 'dayjs'
I agree we should not call `dayjs` directly, and I moved it to `./util/date.js` in 41aa32176b11e1681c8720f1c23a46e5af62343f.

The UTC mode is a tricky one, because in the context of the date picker, the selected dates should be interpreted in the local timezone, and that's why I'm not using `dayjs.utc()`. When using that, the dates get sometimes shifted back 1 day. For now, I decided to move those direct calls to `dayjs` to `./util/date.js` in a function named `parseNaiveDate`.

2023-04-25 09:47 UTC, vinibrsl commented on assets/js/dashboard/datepicker.js
> +            onClose={setCustomDate}
Good question! I was getting multiple `onChange` events when I was developing the date picker for comparisons. As I changed the custom date callback function to somewhat similar what we have for comparisons, I also changed the event to match what we use there. `onClose` gets called only when the modal is closed, and sends the two dates. `onChange` is called whenever a date changes in the date picker.

2023-04-25 11:21 UTC, ukutaht commented on assets/js/dashboard/comparison-input.js
> +import dayjs from 'dayjs'
Thanks, makes sense.

2023-04-25 11:26 UTC, merged