Prevent overwriting with_imported when comparing
plausible/analytics pull request #2871
Opened 2023-04-25 11:38 UTC by vinibrsl

This commit fixes a bug where comparisons would not work with imported data. This is because comparisons copies the source query and modifies the dates only, where it should reevaluate if there is imported data for the new comparison date range.

Closes #2870

2023-04-25 11:41 UTC, aerosol commented on test/support/test_utils.ex
> +  def add_imported_data(%{site: site}, end_at \\ Timex.today()) do
This is unused in your implementation I think? I think import's end date was important in reproducing the bug, let me check

2023-04-25 11:41 UTC, aerosol commented on test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
> +    test "compares imported data and native data together", %{conn: conn, site: site} do
we'll need similar for top-stats too

2023-04-25 11:43 UTC, vinibrsl commented on test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
> +    test "compares imported data and native data together", %{conn: conn, site: site} do
Oops! On it!

2023-04-25 11:43 UTC, aerosol commented on test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
> +    test "compares imported data and native data together", %{conn: conn, site: site} do
porting those tests to `master` doesn't make them fail

2023-04-25 11:47 UTC, aerosol commented on lib/plausible/stats/comparisons.ex
> +    with true <- valid_mode?(source_query, mode),
maybe make this return `:ok | {:error, :not_supported}` so that only a single else clause is then handled?

2023-04-25 11:49 UTC, aerosol commented on priv/repo/seeds.exs
> +Plausible.TestUtils.populate_stats(site, imported_stats_up_to_previous_month)
My takeaway from this is, we should have a plain interface for calling the import pipeline for test purposes, it's currently scattered between controllers and the oban job and it wasn't easy to figure out what function composition was needed in order to create successful import state. Maybe one for a boring day.

2023-04-25 11:53 UTC, aerosol commented on test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
> +             } = json_response(conn, 200)
we'll have to assert the `with_imported` return value here - otherwise the G icon is inactive when current period has no imported data. I took a stab at it with https://github.com/plausible/analytics/blob/fix-comparison-with-imported-stats-in-another-period/lib/plausible_web/controllers/api/stats_controller.ex#L211-L212

2023-04-25 11:55 UTC, aerosol commented on lib/plausible/stats/comparisons.ex
> +    include_imported? = Stats.Query.include_imported?(query, site, opts[:include_imported?])
👍

2023-04-25 13:56 UTC, aerosol requested changes
I think there's still something wrong with it, freshly seeded it shows no chart:

![image](https://user-images.githubusercontent.com/173738/234299582-0a852ba3-029f-4cb5-b71a-8d69e9f5c881.png)

http://localhost:8000/dummy.site?comparison=off&period=month

edit:

only GA stats are visible

![image](https://user-images.githubusercontent.com/173738/234299821-a6b03e43-b19d-4319-b7c3-357f8ad0729c.png)

http://localhost:8000/dummy.site?comparison=off&period=month&with_imported=true&date=2023-03-25

2023-04-25 14:46 UTC, vinibrsl commented
> I think there's still something wrong with it, freshly seeded it shows no chart:
> 
> ![image](https://user-images.githubusercontent.com/173738/234299582-0a852ba3-029f-4cb5-b71a-8d69e9f5c881.png)
> 
> http://localhost:8000/dummy.site?comparison=off&period=month
> 
> edit:
> 
> only GA stats are visible
> 
> ![image](https://user-images.githubusercontent.com/173738/234299821-a6b03e43-b19d-4319-b7c3-357f8ad0729c.png)
> 
> http://localhost:8000/dummy.site?comparison=off&period=month&with_imported=true&date=2023-03-25

I'm a bit confused by this too, but I'm getting this same behavior on master. Do you get it too?

2023-04-25 15:20 UTC, vinibrsl commented
> I think there's still something wrong with it, freshly seeded it shows no chart:
> 
> ![image](https://user-images.githubusercontent.com/173738/234299582-0a852ba3-029f-4cb5-b71a-8d69e9f5c881.png)
> 
> http://localhost:8000/dummy.site?comparison=off&period=month
> 
> edit:
> 
> only GA stats are visible
> 
> ![image](https://user-images.githubusercontent.com/173738/234299821-a6b03e43-b19d-4319-b7c3-357f8ad0729c.png)
> 
> http://localhost:8000/dummy.site?comparison=off&period=month&with_imported=true&date=2023-03-25

I changed the seeds in 44e2efb7ba3dfc71999ee6ce0083ecc618236d89 to make sure native data is not overlapping with imported data. My guess is that this was causing this inconsistent state. Let me know if that solved it for your dataset, please :)

2023-04-26 08:59 UTC, aerosol approved these changes

2023-04-26 09:06 UTC, merged