Add unique constraint to api keys
plausible/analytics pull request #2931
Opened 2023-05-16 13:17 UTC by ukutaht

### Changes

Adds unique constraint to `api_keys` on the `[:user_id, :key_hash]` field combination. This protects from duplicate API keys being created. The UI provides appropriate feedback:

<img width="859" alt="Screenshot 2023-05-16 at 16 15 44" src="https://github.com/plausible/analytics/assets/3731516/020b8c23-8e59-4d33-8de7-b18a73a72797">

2023-05-16 15:44 UTC, vinibrsl commented on test/plausible_web/controllers/auth_controller_test.exs
> +            "name" => "all your code are belong to us",
lol

2023-05-16 15:44 UTC, vinibrsl approved these changes

2023-05-16 15:48 UTC, vinibrsl requested changes

2023-05-16 15:48 UTC, vinibrsl commented on priv/repo/migrations/20230516131041_add_unique_index_to_api_keys.exs
> +    create unique_index(:api_keys, [:user_id, :key_hash])
We have some dupes on the database that need to be deleted before creating the index:

```sql
select user_id, key_hash from api_keys group by user_id, key_hash having count(*) > 1
```

2023-05-17 13:12 UTC, ukutaht commented on priv/repo/migrations/20230516131041_add_unique_index_to_api_keys.exs
> +    create unique_index(:api_keys, [:user_id, :key_hash])
Good call, I've changed the index in https://github.com/plausible/analytics/pull/2931/commits/f07dcd84a32d4b5f275bc1af96e1b5fd99aff2e6

Do you think removing duplicates should be part of the migration? Or a manual fix on the prod database?

2023-05-17 13:16 UTC, vinibrsl commented on priv/repo/migrations/20230516131041_add_unique_index_to_api_keys.exs
> +    create unique_index(:api_keys, [:user_id, :key_hash])
I think it would be best to change the database manually. I haven't checked that, but if we have duplicate entries for different user IDs, we'll have to review each case individually.

2023-05-17 13:17 UTC, vinibrsl approved these changes

2023-05-23 08:37 UTC, merged