Revenue tracking: Add revenue tracking fields to events
plausible/analytics pull request #2949
Opened 2023-05-19 09:23 UTC by vinibrsl

This commit adds 4 fields to the ClickHouse events_v2 table:

* `revenue_source_amount` and `revenue_source_currency` store revenue in the original currency sent during ingestion

* `revenue_reporting_amount` and `revenue_reporting_currency` store revenue in a common currency to perform calculations, and this currency is defined by the user when setting up the goal

2023-05-23 10:48 UTC, ruslandoga commented on priv/ingest_repo/migrations/20230417104025_add_revenue_to_events.exs
> +      add :revenue_reporting_amount, :"Decimal64(4)"
@ukutaht the only downside to decimals I know of is that they are slower than ints (operations on them). Physically they are stored as ints.

2023-05-24 11:05 UTC, ukutaht commented on priv/ingest_repo/migrations/20230417104025_add_revenue_to_events.exs
> +      add :revenue_reporting_currency, :"LowCardinality(FixedString(3))"
> For small fixed values using of LowCardinality is usually inefficient, because ClickHouse stores a numeric index for each row. As a result:
> 
> * Disk space usage can rise.
> * RAM consumption can be higher, depending on a dictionary size.
> * Some functions can work slower due to extra coding/encoding operations.
> * Merge times in MergeTree-engine tables can grow due to all the reasons described above.
> 

Source: https://clickhouse.com/docs/en/operations/settings/settings#allow_suspicious_low_cardinality_types

I think just `FixedString(3)` would be better here.

2023-05-24 11:06 UTC, ukutaht requested changes

2023-05-24 11:06 UTC, ukutaht commented on priv/ingest_repo/migrations/20230417104025_add_revenue_to_events.exs
> +      add :revenue_reporting_currency, :"LowCardinality(FixedString(3))"
Basically the rule seems to be that if the String is less than 8 bytes, LowCardinality will only hurt.

2023-05-24 12:12 UTC, vinibrsl commented on priv/ingest_repo/migrations/20230417104025_add_revenue_to_events.exs
> +      add :revenue_reporting_currency, :"LowCardinality(FixedString(3))"
I didn't know that. Thanks! Changed in 3136e4d5f45200370c584405577ef216abfbc11a

2023-05-26 11:10 UTC, closed without merging

2023-05-26 11:11 UTC, vinibrsl commented
Closed in favor of the discussions in #2957. I'll reopen when we decide on the database type.