Create props settings page
plausible/analytics pull request #3191
Opened 2023-07-25 11:17 UTC by vinibrsl

### Changes

This pull request adds a new settings section for props. Here's a preview:

https://github.com/plausible/analytics/assets/5093045/9d823d75-8879-4d42-a8c1-a16a75dbb2b6

### Tests
- [X] Automated tests have been added

### Changelog
- [X] This PR does not make a user-facing change

### Documentation
- [X] This change does not need a documentation update

### Dark mode
- [X] The UI has been tested both in dark and light mode

2023-07-25 11:21 UTC, vinibrsl commented on lib/plausible_web/live/components/combo_box.ex
> +      x-on:keydown.enter.prevent="select"
The browser default behaviour on a `input[type="text"]` field is to move the cursor from the start to the end of the line when pressing arrow up/down. I added `.prevent` to bypass this - arrow down should open up the dropdown.

2023-07-25 11:23 UTC, vinibrsl commented on priv/repo/migrations/20230724131709_change_allowed_event_props_type.exs
> +      modify :allowed_event_props, {:array, :"varchar(300)"},
300 is the same limit applied to prop keys during ingestion.

2023-07-25 11:34 UTC, aerosol commented on lib/plausible_web/live/components/combo_box.ex
> +      x-on:keydown.enter.prevent="select"
Nice!

2023-07-25 12:38 UTC, aerosol requested changes
Looks nice! I found some edge cases - comments inline

2023-07-25 12:38 UTC, aerosol commented on priv/repo/migrations/20230724131709_change_allowed_event_props_type.exs
> +      modify :allowed_event_props, {:array, :"varchar(300)"},
An attempt of adding long-ish property crashes the connection. And could be truncated perhaps to fit in view.

![image](https://github.com/plausible/analytics/assets/173738/24c18a2f-7a3a-4e94-8ce5-64f273c4b74d)

2023-07-25 12:38 UTC, aerosol commented on lib/plausible_web/templates/site/settings_props.html.heex
> +        Attach custom properties to events
It's probably just me, feel free to disregard. It's confusing, because here I'm supposed to "attach properties to events" but then I can "import properties from existing events". So they were already attached?

2023-07-25 12:38 UTC, aerosol commented on lib/plausible_web/live/props_settings.ex
> +          creatable
![image](https://github.com/plausible/analytics/assets/173738/e175c70a-dcb8-4137-943c-b561d6434c57)

Looks like it's possible to add empty props

2023-07-25 12:38 UTC, aerosol commented on lib/plausible_web/views/layout_view.ex
> +        [key: "Properties", value: "properties"]
We should totally put some emoji on the newly released items 🎁

:D

2023-07-25 12:38 UTC, aerosol commented on lib/plausible_web/live/props_settings.ex
> +  def handle_event("auto-import", _params, socket) do
Have you checked the following scenarios:
  - auto-import from a set of over 300 properties (should there be any feedback that you've reached the limit then?)
  - add manually/auto-import 1 property, then gather more events and auto-import 300
 
?

2023-07-25 12:38 UTC, aerosol commented on lib/plausible_web/live/props_settings.ex
> +  def handle_event("auto-import", _params, socket) do
![image](https://github.com/plausible/analytics/assets/173738/93e2fba9-78e2-4586-9b29-a489d52e211b)

2023-07-26 08:46 UTC, vinibrsl commented on lib/plausible/ingestion/request.ex
> +  @max_prop_value_length Plausible.Props.max_prop_value_length()
Yes! `lib/plausible/ingestion/request.ex` is recompiled when changing `lib/plausible/props.ex`.

2023-07-26 08:50 UTC, aerosol commented on lib/plausible_web/templates/site/settings_props.html.heex
> +      router: PlausibleWeb.Router
This option does nothing. I'll remove it from funnel's live_render too.

2023-07-26 08:53 UTC, vinibrsl commented on lib/plausible/props.ex
> +    allowed_event_props = site.allowed_event_props || []
I initially thought of this, but we still need to make distinction between empty lists and nils. For compatibility, there are dashboard queries that keep the "old" custom props behavior when `nil`, e.g. https://github.com/plausible/analytics/blob/master/lib/plausible/stats/custom_props.ex#L48

2023-07-26 08:53 UTC, aerosol commented on lib/plausible/props.ex
> +    allowed_event_props = site.allowed_event_props || []
Thanks for clarification.

2023-07-26 08:58 UTC, vinibrsl commented on lib/plausible_web/templates/site/settings_props.html.heex
> +      router: PlausibleWeb.Router
Removed in 285645ad396e608a75dfe4621c6b36df73ce3830

2023-07-26 08:58 UTC, vinibrsl commented on lib/plausible/props.ex
> +  def enabled_for?(%Plausible.Auth.User{} = user) do
Good call! Changed in 587030b8

2023-07-26 19:15 UTC, vinibrsl commented on lib/plausible_web/live/props_settings.ex
> +          creatable
Oops! Should be fixed in 1d7bf7dc

2023-07-26 19:15 UTC, vinibrsl commented on lib/plausible_web/live/props_settings.ex
> +      |> get_site(socket.assigns.domain)
Good call! Changed in c6e15a43.

2023-07-26 19:15 UTC, vinibrsl commented on lib/plausible_web/live/props_settings.ex
> +        Or auto-import properties from your events
Good catch! eec4c777 fixes the bug and adds a test case

2023-07-26 20:56 UTC, vinibrsl commented on priv/repo/migrations/20230724131709_change_allowed_event_props_type.exs
> +      modify :allowed_event_props, {:array, :"varchar(300)"},
Good catch! 74e3f7906a28cb0e19f9945f137a7d8cd9541745 limits the dropdown width to the input element.

https://github.com/plausible/analytics/assets/5093045/5bac8cc2-4432-4ad7-9b45-db3a65416546

2023-07-26 21:02 UTC, vinibrsl commented on lib/plausible_web/live/components/combo_box.ex
> +      x-on:keydown.arrow-up.prevent="focusPrev"
Good call! I also think the first <kbd>Enter</kbd> should select from the dropdown, while the second <kbd>Enter</kbd> should submit the form. I initially tried doing this, but I had problems with the page focus, so I decided to go with the "easiest but not terrible" (tm) solution which is <kbd>Enter</kbd> interacts with the combo box dropdown only. I still want to try making this work, but do you think it's okay to file it as improvement for later?

2023-07-26 21:08 UTC, vinibrsl commented on lib/plausible_web/live/props_settings.ex
> +                <svg
This button permanently removes the prop from the allow list. Removed props often reappear in the suggestions list because there are events with that prop name on ClickHouse. Do you think adding a confirmation prompt is enough in this case?

2023-07-27 07:16 UTC, aerosol commented on lib/plausible_web/live/components/combo_box.ex
> +      x-on:keydown.arrow-up.prevent="focusPrev"
> but do you think it's okay to file it as improvement for later?

Sure thing! Maybe check with others too, I'd consider removing the "Add" button and saving the choice upon selection.

2023-07-27 07:19 UTC, aerosol commented on lib/plausible_web/live/props_settings.ex
> +                <svg
> Do you think adding a confirmation prompt is enough in this case?

Or a tooltip? I don't have a strong opinion on that one, just wanted to flag it for your consideration.

2023-07-27 07:20 UTC, aerosol commented on priv/repo/migrations/20230724131709_change_allowed_event_props_type.exs
> +      modify :allowed_event_props, {:array, :"varchar(300)"},
Nice!

2023-07-27 07:23 UTC, aerosol commented on lib/plausible_web/live/props_settings.ex
> +    {:ok, site} = Plausible.Props.allow(socket.assigns.site, prop)
Cool. I think what's left is handling the changeset error cases. 

I'm also wondering is there a reason for internal interfaces using allow/disallow terminology but no similar phrasing in the UI. Was this intentional?

2023-07-27 08:33 UTC, vinibrsl commented on lib/plausible_web/live/props_settings.ex
> +                <svg
What do you think, @RobertJoonas?

2023-07-27 10:15 UTC, vinibrsl commented on lib/plausible_web/live/props_settings.ex
> +    {:ok, site} = Plausible.Props.allow(socket.assigns.site, prop)
> Cool. I think what's left is handling the changeset error cases.

Changeset error cases added in 814ce44.

> I'm also wondering is there a reason for internal interfaces using allow/disallow terminology but no similar phrasing in the UI. Was this intentional?

Thanks for pointing that out! When I started working on this, the `sites.allowed_event_props` field was already in the database, so I decided to follow its terminology: allowed -> allow/disallow.

However, when designing the UI, I felt those terms might be confusing for our users. Instead of focusing on what’s allowed or not, I wanted users to understand the actual workflow: users first create properties in the dashboard using the settings page, and then send them via the API. If they don't, the properties won't appear on the dashboard. And just to clarify, this allow list only affects ClickHouse queries and not the ingestion process as we don't want to drop any data.

2023-07-27 10:16 UTC, vinibrsl commented on lib/plausible_web/live/props_settings.ex
> +  def handle_event("auto-import", _params, socket) do
Good catch! 814ce440f3b811b45e57265a030d515fd53d2521 adds changeset validations and a test case covering this.

2023-07-27 10:22 UTC, vinibrsl commented on lib/plausible_web/templates/site/settings_props.html.heex
> +        Attach custom properties to events
I see what you mean and I also think it's not the best subtitle. Do you think "Track custom properties from events" is a better name?

2023-07-27 10:55 UTC, aerosol commented on lib/plausible_web/live/props_settings.ex
> +    {:ok, site} = Plausible.Props.allow(socket.assigns.site, prop)
Oh that makes sense, thank you. Would you mind leaving that explanation somewhere in the code comments? I think this is pretty much the context I was missing.

2023-07-27 10:57 UTC, aerosol commented on lib/plausible_web/templates/site/settings_props.html.heex
> +        Attach custom properties to events
> "Track custom properties from events"

Yeah that sounds much better IMHO. Paging @metmarkosaric

2023-07-27 11:02 UTC, RobertJoonas commented on lib/plausible_web/live/props_settings.ex
> +                <svg
> What do you think, @RobertJoonas?

Since configuring props is only a UI thing and it doesn't affect any actual data, I think confirmation popups would be annoying and redundant. Also, personally I don't see much value in tooltips.

But I do agree with what @aerosol said in another comment here:

> It's probably just me, feel free to disregard. It's confusing, because here I'm supposed to "attach properties to events" but then I can "import properties from existing events". So they were already attached?

I feel like "Attaching" custom properties to events is a separate and a much more complex part of this feature. To start sending props to Plausible, people need to dig deeper into docs.

Instead of "_Attach custom properties to events_", how about something like:

"_You can attach custom properties to all your events to analyze metrics we don't track automatically. Check out our documentation about sending custom properties to Plausible. In order for the properties to show up on your dashboard, you need to explicitly add them in the below menu first._"

Also, what do you think about changing the auto-import link to something like:

Already sent custom properties to Plausible? [Import from existing events](https://dontclick.me/

2023-07-27 11:11 UTC, aerosol approved these changes
Nice work! 👏

I'm only wondering if there should be a user interface to "remove all", in case people set up many props and want to start from scratch.

I was trying to do that from the shell, to test the UI, and it took me a while to realise that `disallow` doesn't accept `prop_or_props` (it silently fell back to no change). 

Maybe something for another iteration.

2023-07-27 11:18 UTC, RobertJoonas commented on lib/plausible_web/live/props_settings.ex
> +    {:ok, site} = Plausible.Props.allow(socket.assigns.site, prop)
> I'm also wondering is there a reason for internal interfaces using allow/disallow terminology but no similar phrasing in the UI. Was this intentional?

Good point... I think the reason I went with the `allowed_event_props` field name was that we were working on "filtering out garbage props" at the time. Since I believe this field is not used by anyone else other than ourselves, now is probably a good time to change the name. How about just `site.event_props`?

2023-07-27 11:19 UTC, RobertJoonas commented on lib/plausible_web/live/props_settings.ex
> +    {:ok, site} = Plausible.Props.allow(socket.assigns.site, prop)
Although from the backend perspective it does make sense that the props are "allowed" to show up on the dashboard. Dunno, it's fine by me to keep the current name too...

2023-07-27 11:29 UTC, RobertJoonas commented on lib/plausible_web/templates/site/settings_props.html.heex
> +        Attach custom properties to events
Same convo going on in two places, so dropping [a link](https://github.com/plausible/analytics/pull/3191#discussion_r1276121008) here to my other comment in an above discussion (/cc @metmarkosaric).

Do you guys think a text like:

> You can attach custom properties to all your events to analyze metrics we don't track automatically. Check out our documentation about sending custom properties to Plausible. In order for the properties to show up on your dashboard, you need to explicitly add them in the below menu first.

would be too long?

2023-07-27 13:04 UTC, metmarkosaric commented on lib/plausible_web/live/props_settings.ex
> +                <svg
@RobertJoonas how about this for the subheading:

"Attach custom properties when sending a pageview or an event to create custom metrics."

we do something like this in goals section and it's worth adding here too to minimize confusion:

"Custom properties are not tracked by default - you have to configure them on your site to be sent to Plausible. See examples and learn more in our docs."

about the auto-import: does it import any property already sent to us both on the event and pageview level or only custom event level? I think best not to talk about it as "import" as it confuses things. perhaps this could work for it:

"Already sending custom properties? Click to show all existing properties"

> Since configuring props is only a UI thing and it doesn't affect any actual data, I think confirmation popups for removing the props from the list would be annoying and redundant. Also, personally I don't see much value in tooltips.

I see we already do a confirmation in the goals section when trying to delete a goal so best to keep it consistent with what we already do

it's always a good idea to keep the user interface as close as possible and consistent with what we already do other relevant places. in this case the new props settings section basically has the same purpose as the existing goals settings section. both these sections do the same for the user: they allow them to configure a specific section of the dashboard and add or remove specific entries from being shown in the dashboard. so the more consistent they are the easier it is to understand and use them

2023-07-27 13:10 UTC, metmarkosaric commented on lib/plausible_web/templates/site/settings_props.html.heex
> +        Attach custom properties to events
@RobertJoonas I responded to the other comment here https://github.com/plausible/analytics/pull/3191#discussion_r1276252588

2023-07-27 14:46 UTC, merged