Display premium features tabs on the dashboard
plausible/analytics pull request #3646
Opened 2023-12-20 12:13 UTC by vinibrsl

This commit makes the funnels and props tab on the dashboard visible even when the site owner's plan does not have access to that feature. This is to raise awareness of those features, and if the site owner does not want to see that tab, they can still click "Hide this report" to hide it.

Previously, when the plan did not support a feature, the feature module `enabled/1` function returned `false`, regardless of the `sites.feature_enabled` toggle. This commit creates a new function called `opted_out/1` to differentiate access from explicitly opting out a feature.

2023-12-20 17:07 UTC, RobertJoonas requested changes
I tested it out on staging and it looks like we're currently not allowing the user to opt out of a feature that they don't have access to.

I clicked on the "Hide this report" button (for Funnels) in the feature setup notice and nothing happened (I was on a Growth plan). I expected the feature notice setup to disappear.

Left some comments inline as well with some suggestions.

2023-12-20 17:07 UTC, RobertJoonas commented on lib/plausible/billing/feature.ex
> +      end
The same condition is actually repeated on lines 114 and 115. What do you think about rewriting the cond clause into this instead:

```elixir
check_availability(site.owner) == :ok && not opted_out?(site)
```

2023-12-21 14:18 UTC, vinibrsl commented on lib/plausible/billing/feature.ex
> +      end
Good call! Changed in 81fdd861e574026e02241b414d81af7d1f8b06b1

2023-12-21 14:18 UTC, vinibrsl commented on lib/plausible_web/templates/stats/stats.html.eex
> +    data-conversions-available="<%= Plausible.Billing.Feature.Goals.check_availability(@site.owner) == :ok %>"
Changed in d1025b1e7bb7702bf46e37db2875bfd381ed7055

2023-12-21 14:18 UTC, vinibrsl commented on assets/js/dashboard.js
> +    conversionsAvailable: container.dataset.conversionsAvailable === 'true',
Changed in d1025b1e7bb7702bf46e37db2875bfd381ed7055

2023-12-21 14:19 UTC, vinibrsl commented
> I clicked on the "Hide this report" button (for Funnels) in the feature setup notice and nothing happened (I was on a Growth plan). I expected the feature notice setup to disappear.

Oops! I fixed this bug in dc97e83de412a08a5f77cf77f3ac2d56b615d060.

2023-12-30 16:45 UTC, RobertJoonas approved these changes

2024-01-03 11:32 UTC, merged