[WIP] Latency-friendly LV modal implementation
plausible/analytics pull request #3649
Opened 2023-12-21 15:38 UTC by zoldar

### Changes

Please describe the changes made in the pull request here.

Below you'll find a checklist. For each item on the list, check one option and delete the other.

### Tests
- [ ] Automated tests have been added
- [ ] This PR does not require tests

### Changelog
- [ ] Entry has been added to changelog
- [ ] This PR does not make a user-facing change

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated
- [ ] This change does not need a documentation update

### Dark mode
- [ ] The UI has been tested both in dark and light mode
- [ ] This PR does not change the UI

2023-12-21 15:51 UTC, zoldar commented on assets/js/app.js
> +  window.addEventListener(`phx:close-modal`, (e) => {
This event listener allows hiding modal from the backend using `Modal.close/2`

2023-12-21 15:53 UTC, zoldar commented on extra/lib/plausible_web/live/funnel_settings/form.ex
> +                    end}
A problem with implicit send surfaced while working on the modal. As this message is used only in some uses of ComboBox, it made sense to make it optional, so that caller is not forced to implement noop `handle_info` clause just for that. Additionally, callback approach allows for greater flexibility.

2023-12-21 15:55 UTC, zoldar commented on lib/plausible_web/live/components/modal.ex
> +  end
Closing the modal outside normal input events is largely something initiated from the backend, so `close/2` is exposed as the only way to do that programmatically for now.

2023-12-21 15:57 UTC, zoldar commented on lib/plausible_web/live/components/modal.ex
> +      class="[&[data-phx-ref]_div.modal-dialog]:hidden [&[data-phx-ref]_div.modal-loading]:block"
CSS assures immediate loading state application the moment state change is dispatched to the backend. It also lets us avoid "flicker" issues when modal is rapidly closed and opened again.

2023-12-21 15:58 UTC, zoldar commented on lib/plausible_web/live/components/modal.ex
> +        }
This way of "duplicated" management of modal state allows for responsiveness while assuring full reload of contents when needed.

2023-12-21 16:01 UTC, zoldar commented on lib/plausible_web/live/components/modal.ex
> +          <div class="text-center max-w-md w-full mx-auto bg-white dark:bg-gray-800 shadow-md rounded px-8 pt-6 pb-8 mb-4 mt-8">
Styling will most likely have to be made customizable here, so that loading status at least preserves the width of the loaded modal.

2023-12-21 16:02 UTC, zoldar commented on lib/plausible_web/live/goal_settings/form.ex
> +  use Phoenix.LiveComponent
Turned it into a LiveComponent in the process while iterating on previous approaches to responsive modal. It does not have to be a full-fledged liveview anyway and it also slightly simplifies logic IMHO.

2023-12-21 16:04 UTC, zoldar commented on lib/plausible_web/live/goal_settings/form.ex
> +        <.tabs tabs={@tabs} myself={@myself} />
Tabs will need changing with either an explicit loading state when switching or managing them on frontent entirely. Both ways are viable I think. Anyways, that's a bit beside the scope of that experiment but should be addressed eventually.

2023-12-21 16:05 UTC, zoldar commented on lib/plausible_web/live/goal_settings/form.ex
> +          |> socket.assigns.on_save_goal.(socket)
Implementing callback here for better flexibility.

2023-12-21 16:07 UTC, zoldar commented on lib/plausible_web/live/goal_settings.ex
> +            end
Callback enables greater flexibility. Also, the form component is now completely agnostic to the context it is put in and matters of handling added goal and managing modal state are kept separate.

2024-01-09 09:56 UTC, zoldar commented on lib/plausible_web/live/components/modal.ex
> +          liveSocket.execJS($el, $el.dataset.onopen);
Sending those events consecutively one after another allows to consistently reset modal state while avoiding race conditions.

2024-01-10 12:13 UTC, aerosol approved these changes
Looks good, two minor issues:

- clicking outside of the modal in the highlighted area feels random - sometimes does close the modal, sometimes it doesn't

![image](https://github.com/plausible/analytics/assets/173738/142e7d0d-244a-4177-9ab4-653229d90e0c)

- Since the selection messages are unnecessary, we can also revert the test change done at https://github.com/plausible/analytics/pull/3675/commits/46f65d9adb9dd220f6043e6589fc48865a905710

2024-01-10 12:13 UTC, aerosol commented on lib/plausible_web/live/components/modal.ex
> +      qouted above shows one way to implement this, under that assumption
```suggestion
      quoted above shows one way to implement this, under that assumption
```

2024-01-10 14:10 UTC, zoldar commented
@aerosol I have fixed and cleaned up modal styling, especially on small/mobile screens. It also addresses problem with active areas for clicking "outside" the dialog window.

Before (what's currently in prod too 🙈 ):

<img width="393" alt="image" src="https://github.com/plausible/analytics/assets/588351/a9446e00-c76d-4a33-ad7f-ce7bb2dabc9d">

After:

<img width="399" alt="image" src="https://github.com/plausible/analytics/assets/588351/c6d4784b-a73b-44d7-a95c-82e93c8b7633">

Done in https://github.com/plausible/analytics/pull/3649/commits/3664027671546148d5c5676290b6e5016375e0c2

2024-01-11 12:48 UTC, zoldar commented
Following changes were applied:

* Show a spinner directly on backdrop instead of in a dialog
* Both spinner and dialog centered vertically in the viewport
* Scroll should be trapped within the modal (like details views on the dashboard)
* Focus should be trapped within the modal (Phoenix.Component.focus_wrap/1)
* Enter/leave transitions, shadow, border radius from https://tailwindui.com/components/application-ui/overlays/dialogs#component-a522f43bd52fbf6391e2273163eec330

2024-01-15 09:16 UTC, aerosol requested changes
There's a bit inconsistent behavior now with regards to the modal placement - in goals, it shows exactly in the center now:

![image](https://github.com/plausible/analytics/assets/173738/0d0991d0-beee-4dd3-9253-0b040937fc6c)

vs custom props for example:

![image](https://github.com/plausible/analytics/assets/173738/1046a848-e763-4783-9ccd-e2b1b932cd81)

This dynamic (?) alignment makes it look glitchy when switching tabs:


https://github.com/plausible/analytics/assets/173738/3fdfa880-a3e8-4ff7-a670-04840208c96b

2024-01-15 10:33 UTC, zoldar commented
https://github.com/plausible/analytics/pull/3649/commits/653a256d14b05bdf91258c1535d31b42481f7425 brings back top-alignment.

Before:

https://github.com/plausible/analytics/assets/588351/e59ad3ab-a400-41a5-b806-88c65b8a1601

After:


https://github.com/plausible/analytics/assets/588351/39c612de-0b5c-46b7-ba8d-d06edfc63a5d

2024-01-15 10:39 UTC, merged