Set exit_page only on pageviews
plausible/analytics pull request #3870
Opened 2024-03-07 15:11 UTC by macobo

### Changes

Previously we set and updated `exit_page` on all events, which can cause issues when:
1. Sessions without any pageviews are made (e.g. user leaves a tab open and returns to it)
2. It results in exit_page exit_rate calculations returning numbers above 100

Additional context under https://3.basecamp.com/5308029/buckets/35611491/card_tables/cards/7162713530

### Tests
- [x] Automated tests have been added
- [ ] This PR does not require tests

### Changelog
- [x] Entry has been added to changelog
- [ ] This PR does not make a user-facing change

2024-03-07 17:14 UTC, aerosol requested changes
Would be good to look into those test failures. Can't quickly tell if it's a fixture error, a regression or if there's something easily abused with the way we populate test data.

2024-03-08 07:11 UTC, macobo commented
Test failures were real - we were creating Signup events in the relevant tests.

Given that this also affects bounce rates, etc as per these example tests, it would be great to have @ukutaht's input before merging this.

> but it seems to also require updating how we query for stats so that we filter out custom events-only sessions from breakdowns/aggregates in which they do not apply

I'm considering that a separate task that's slightly trickier than this given the wide-reaching ramifications. I was planning to make sure this gets a satisfying solution, but is less urgent than this fix. If you have input/thoughts or want to lead that feel free! :bow:

2024-03-14 07:53 UTC, ukutaht approved these changes

2024-03-14 07:53 UTC, ukutaht commented on test/plausible/session/cache_store_test.exs
> +    assert session.exit_page == "/path/2"
For extra clarity I think this test could also assert that `session.entry_page == ""`

2024-03-14 07:55 UTC, ukutaht commented
Wait, I approved too early. Why does this affect bounce rates? 👀

2024-03-14 09:34 UTC, ukutaht commented
As per [https://3.basecamp.com/5308029/buckets/35611491/card_tables/cards/7162713530#__recording_7186457996](discussion), this solution is good. Let's do it!

2024-03-14 10:03 UTC, macobo commented on test/plausible/session/cache_store_test.exs
> +    assert session.exit_page == "/path/2"
This brings up a question: Should we also update entry_page on a subsequent event if a) it's a pageview and b) session doesn't have entry_page set?

2024-03-14 10:09 UTC, ukutaht commented on test/plausible/session/cache_store_test.exs
> +    assert session.exit_page == "/path/2"
> After re-visiting I think we should set exit_page to /path/2 here as well, thoughts?

you mean entry_page rather than exit_page, right?

Yeah I think that does make sense. Then entry page and exit page will always correspond to the first and last pageview in a session which feels intuitive to me.

2024-03-18 09:11 UTC, merged