Implement search in Details views
plausible/analytics pull request #4318
Opened 2024-07-08 08:19 UTC by RobertJoonas

### Changes

* Refactor the structure of a metric on the frontend - use a Metric class with special creator functions.
* Create a higher-order component for keeping the query context (such as the query object itself and additional information such as `revenueAvailable`, `importedDataInView`, `lastLoadTimestamp`)
* Create a new BreakdownModal component that includes the search functionality, and make all current "Details" view modals to use it.
  * Note: some API endpoints (goals, countries, regions, cities) do not support a contains filter. This PR will start using the new BreakdownModal in those reports too, but the search is explicitly disabled via `enableSearch={false}` prop.

### Tests
- [x] This PR does not require tests

### Changelog
- [ ] Entry has been added to changelog

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated

### Dark mode
- [ ] The UI has been tested both in dark and light mode

2024-07-08 11:44 UTC, apata commented on assets/js/dashboard/components/query-context-hoc.js
> +    const [revenueAvailable, setRevenueAvailable] = useState(false)
**nitpick**: I had a closer look at `revenueAvailable,` and based on my reading, it's a calculated value. One of the principles of React state is for it not to contain anything duplicated or redundant ([reasoning](https://react.dev/learn/managing-state#choosing-the-state-structure)), and a value you can calculate is redundant. Therefore, I'm suggesting we remove the useState hook and calculate the value directly. If the calculation is expensive, we can use useMemo to limit its recalculation.

2024-07-08 11:48 UTC, apata commented on assets/js/dashboard/components/query-context-hoc.js
> +      setRevenueAvailable(revenueGoalsInFilter.length > 0 && singleCurrency)
**suggestion**: I'm loving the way you refactored some of the responsibility that was in component render code to a separate but colocated utility function (chooseMetrics). 

Would that be possible with this code as well? A separate unit-testable `function shouldShowRevenueAvailable(...)` would I think increase code readability and future maintainability.

2024-07-08 12:04 UTC, RobertJoonas commented on assets/js/dashboard/components/query-context-hoc.js
> +    const [revenueAvailable, setRevenueAvailable] = useState(false)
Thanks, @apata. Makes perfect sense! I've created a new `revenueAvailable` predicate function in https://github.com/plausible/analytics/pull/4318/commits/601b849e2796a5739e2d3752a497cbb2f8609634

2024-07-08 12:24 UTC, ukutaht requested changes

2024-07-08 12:24 UTC, ukutaht commented on assets/js/dashboard/stats/modals/breakdown-modal.js
> +  const fetchData = useCallback(debounce(() => {
I don't think the debounce here is working as it should.

The idea with debouncing search queries is that if I write a phrase quickly into the search box, the intermediate results are not requested. Only the full phrase is searched once.

But when I write 'long' into the search box using our seeds, I see 4 requests in the network tab:
* Search with `page: 'l'`
* Search with `page: 'lo'`
* Search with `page: 'lon'`
* Search with `page: 'long'`


When it should only fire a single API request for:
* Search with `page: 'long'`

I think the debounce function should be used before the `onChange` handler fires so that the `search` prop is only updated after the debounce step.

2024-07-09 10:22 UTC, macobo commented on assets/js/dashboard/query.js
> +      return clauses.includes(rg.event_name)
Can't revenue goals be pageview goals?

2024-07-09 10:24 UTC, macobo commented on assets/js/dashboard/stats/reports/list.js
> +              onClick={props.onClick || noop}
Why is the || noop needed? Can't the FilterLink component handle undefined as others do usually?

2024-07-09 10:25 UTC, macobo commented on assets/js/dashboard/stats/modals/props.js
> +  const addSearchFilter = useCallback((query, s) => {
Nit: `s` -> `searchPhrase`.

2024-07-09 10:29 UTC, macobo commented on assets/js/dashboard/stats/modals/locations-modal.js
> +  if (currentView === 'countries') {
Not sure this works as intended - IIRC using conditionals like this in react can cause issues.

I'd instead use `useMemo(() => ..., [currentView])` or extract subcomponent.

2024-07-09 10:32 UTC, macobo commented on assets/js/dashboard/stats/modals/breakdown-modal.js
> +  } = props
Nit: `props.something` is _almost_ not used below.

I'd move this deconstruction into the function header.

2024-07-09 10:33 UTC, macobo commented on assets/js/dashboard/stats/modals/breakdown-modal.js
> +  const isSearchEnabled = searchEnabled === false ? false : true
What's going on here?

Why not use `searchEnabled` prop directly? Is it to do with defaults.

2024-07-09 10:40 UTC, RobertJoonas commented on assets/js/dashboard/query.js
> +      return clauses.includes(rg.event_name)
Revenue goals are always custom event goals.

2024-07-09 11:38 UTC, RobertJoonas commented on assets/js/dashboard/stats/modals/locations-modal.js
> +  if (currentView === 'countries') {
Moved the conditionals into the map defining the report info. https://github.com/plausible/analytics/pull/4318/commits/c739005e371db27aa4be0aac59e8e2a0e01a35b1

2024-07-09 11:48 UTC, RobertJoonas commented on assets/js/dashboard/stats/modals/props.js
> +  const addSearchFilter = useCallback((query, s) => {
Did a few renamings and wrote out the whole word instead of `s` and `m`. https://github.com/plausible/analytics/pull/4318/commits/0efc3c9422a8470784c53484458b5fd8ccf5ac3d

2024-07-09 11:48 UTC, RobertJoonas commented on assets/js/dashboard/stats/modals/breakdown-modal.js
> +  } = props
Good call. Done in https://github.com/plausible/analytics/pull/4318/commits/016245f007ea640150642ac46b8c54d8249b5140

2024-07-09 11:49 UTC, RobertJoonas commented on assets/js/dashboard/stats/modals/breakdown-modal.js
> +  const isSearchEnabled = searchEnabled === false ? false : true
Yeah, it's supposed to be `true` by default. Found a better way to express that now in https://github.com/plausible/analytics/pull/4318/commits/78e44fa256db92b32c2d4b31c6fe5709f71b90fd

2024-07-09 12:01 UTC, ukutaht approved these changes

2024-07-09 12:01 UTC, merged