update postgrex config
plausible/analytics pull request #4460
Opened 2024-08-21 07:15 UTC by ruslandoga

### Changes

This PR removes `ssl_opts` that are no longer necessary after https://github.com/elixir-ecto/postgrex/pull/677

### Tests
- [x] This PR does not require tests

### Changelog
- [x] This PR does not make a user-facing change

### Documentation
- [x] This change does not need a documentation update

### Dark mode
- [x] This PR does not change the UI

2024-08-21 07:18 UTC, aerosol approved these changes

2024-08-21 07:19 UTC, aerosol requested changes
hmm CI says no

2024-08-21 07:20 UTC, ruslandoga commented
Hm, it seems like the behaviour has actually changed slightly. Previously `ssl_opts` were only applied when `ssl` connection was specified elsewhere, and now the new `ssl` opts actually force the `ssl` connection.

2024-08-30 09:57 UTC, cnkk approved these changes

2024-08-30 10:11 UTC, merged