Limit docs query API, return 401 for API routes
plausible/analytics pull request #4570
Opened 2024-09-11 07:29 UTC by macobo

### Changes

After this:
- Docs Query API routes are not queriable by viewers/public
- API routes return a JSON error over html page

Solves https://3.basecamp.com/5308029/buckets/37310803/card_tables/cards/7782351091

There might be a follow-up docs change to tweak behavior when user has insufficient access or isn't logged in.

### Tests
- [x] Automated tests have been added
- [ ] This PR does not require tests

### Changelog
- [x] Entry has been added to changelog
- [ ] This PR does not make a user-facing change

2024-09-11 08:56 UTC, apata commented on lib/plausible_web/plugs/authorize_site_access.ex
> +      Keyword.get(options, :api, false)
**meganitpick, non-blocking**: api is a bit general term: it won't be obvious that the error response style (html or json) is wired on it. 

If we need to branch for error formats, I'd advise respecting the request "accept" header. 

To prevent JSON APIs from serving html errors, I'd also reject requests that don't carry the accept header expected for the route. It's a bit of work adding the request accept validation to each pipeline / route, but it's standard (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406).

2024-09-11 09:00 UTC, apata approved these changes

2024-09-11 09:35 UTC, macobo commented on lib/plausible_web/plugs/authorize_site_access.ex
> +      Keyword.get(options, :api, false)
What you're suggesting makes sense but seems rabbit-holey. I'll keep this in mind but not go down this route (yet).

2024-09-11 10:00 UTC, aerosol commented on lib/plausible_web/plugs/authorize_site_access.ex
> +  alias PlausibleWeb.Api.Helpers, as: H
just import?

2024-09-11 10:09 UTC, aerosol commented on lib/plausible_web/plugs/authorize_site_access.ex
> +      Keyword.get(options, :api, false)
Whether it comes from the API or not should be differentiated based on conn rather than compile-time marker?

Halting the connection with HTTP status should result with error view being applied based on accept header as @apata suggests (via `PlausibleWeb.ErrorView`, no?).

2024-09-11 10:29 UTC, macobo commented on lib/plausible_web/plugs/authorize_site_access.ex
> +      Keyword.get(options, :api, false)
@aerosol sorry I'm lost, what is it you're suggesting?

2024-09-11 10:35 UTC, aerosol commented on lib/plausible_web/plugs/authorize_site_access.ex
> +      Keyword.get(options, :api, false)
let me try something, will get back to you

2024-09-12 07:44 UTC, zoldar commented on lib/plausible_web/plugs/authorize_site_access.ex
> +      Keyword.get(options, :api, false)
We can use `(Phoenix.Controller).get_format(conn)` to get the negotiated content type set by `:accept` plug, with a fallback, just in case, like this:

```elixir
format = get_format(conn) || "html"
```

and use it to determine which error format to send ("json" or "html" in this case) - that should remove the need for explicit `api` option I think. We could go even further and modify `PlausibleWeb.ControllerHelpers.render_error/2,3` to detect format on its own. However, as is, this plug returns 404 for web/HTML and 401 for API/JSON - maybe we could settle on 404 for both for instance?

2024-09-12 07:53 UTC, macobo commented on lib/plausible_web/plugs/authorize_site_access.ex
> +      Keyword.get(options, :api, false)
Thanks @zoldar! I was initially hesitant since we hadn't done anything like this in the codebase and I was unsure of the complexity. Your proposal helps though.

> However, as is, this plug returns 404 for web/HTML and 401 for API/JSON - maybe we could settle on 404 for both for instance?

I'd argue it makes sense. Consider the two usecases:
1. User is not logged in and tries to open a settings page - 404
2. User is logged in and does not have access to that site - 404 still makes sense but is a bit more dubious
3. Someone has logged in but browser requests internal stats API - I'd argue 401 makes more sense, but can be convinced otherwise.
4. Logged in user tries to use [Stats APIv2 playground](https://plausible.io/docs/stats-api-playground) but mistypes the site_id - returning 404 wouldn't make sense in that scenario and would confuse the UX of the playground. A 401 - Forbidden with an error message makes more sense.

2024-09-12 08:21 UTC, zoldar commented on lib/plausible_web/plugs/authorize_site_access.ex
> +      Keyword.get(options, :api, false)
What's the difference between 2 and 3? Anyways, in all 4 cases we are talking about authenticated user who has _no_ access to a given site (regardless whether they try to request it delibarately or due to a typo), correct? The whole point of returning 404 is to avoid leaking the fact that stats for a given site are in the system to any unauthorized party. With that in mind, I'd argue 404 is the appropriate error to return in all those cases.

2024-09-12 08:40 UTC, macobo commented on lib/plausible_web/plugs/authorize_site_access.ex
> +      Keyword.get(options, :api, false)
I've changed it to return 404 over 401 now and changed the error message to accomodate. It still feels off but simplifies the PR significantly. Thanks!

2024-09-12 08:54 UTC, zoldar approved these changes

2024-09-12 08:58 UTC, apata requested changes

2024-09-12 08:58 UTC, apata commented on CHANGELOG.md
> +- Internal stats API routes now return 401 over 404 in case of invalid access.
typo: not accurate any more, right?

2024-09-12 08:58 UTC, zoldar commented on CHANGELOG.md
> +- Internal stats API routes now return 401 over 404 in case of invalid access.
ah, well spotted 🙈

2024-09-12 09:03 UTC, apata commented on CHANGELOG.md
> +- Internal stats API routes now return 401 over 404 in case of invalid access.
```suggestion
```

2024-09-12 11:01 UTC, macobo commented on CHANGELOG.md
> +- Internal stats API routes now return 401 over 404 in case of invalid access.
Good eyes. Changed this to `Internal stats API routes now return a JSON error over HTML in case of invalid access.`

2024-09-12 11:11 UTC, merged