Adds dark mode to entire dashboard
plausible/analytics pull request #467
Opened 2020-12-13 10:59 UTC by Vigasaurus

### Changes

Adds dark mode user option and system setting adherence across the entirety of the dashboard and otherwise authenticated user flows.

I do have this currently running at https://dev.vigneshjoglekar.com/plausible.io - but this is my personal VPS for all staging+my VS Code server so it could easily be down at random times. The benefit here is that I've got the real plausible demo data being pulled in, to make testing easier. (Feel free to let me know if its ever down and I can get it spun back up). 

Definitely do let me know if there are any issues or missing elements etc - I'd be happy to get them resolved!

### Tests
My Elixir is weak at best, I'm mostly unsure how/where exactly I'd add tests for my changes. I imagine it'd only be for the extra column in the user table, and its modification - but I'm unsure. I did also have to add a migration. 

### Changelog
- [X] Entry has been added to changelog

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated
Again, I'm unsure if this needs any documentation change - besides maybe the contributors section 😉

### Screenshots
![image](https://user-images.githubusercontent.com/19434157/102009678-b15db400-3cfe-11eb-8ef1-561f0dbb2cd0.png)
![image](https://user-images.githubusercontent.com/19434157/102009681-b3c00e00-3cfe-11eb-844f-fb10b4834fa1.png)
![image](https://user-images.githubusercontent.com/19434157/102009682-b4f13b00-3cfe-11eb-8148-54a6430ffb15.png)
![image](https://user-images.githubusercontent.com/19434157/102009684-ba4e8580-3cfe-11eb-8624-a4779da25745.png)

2020-12-14 08:10 UTC, rjgamer commented
I like the dark gray styles more, but your blueish style looks cool too. Good job!

2020-12-14 08:25 UTC, ukutaht commented
Looks great

2020-12-14 08:28 UTC, Vigasaurus commented
Thanks! To be fair, most of my color choices revolve around the [mockup](https://github.com/plausible/analytics/discussions/115#discussioncomment-179770) that NuroDev made.

2020-12-14 15:22 UTC, ukutaht commented
@Vigasaurus ready for review?

2020-12-14 17:12 UTC, Vigasaurus commented
Yep 👍

2020-12-15 11:02 UTC, ukutaht requested changes
Looks good, I'm eager to merge. I have a few comments that I'd like to hash out, let's discuss further in replies to those individual comments.

2020-12-15 11:02 UTC, ukutaht commented on lib/plausible/themes.ex
> +  @moduledoc "https://stackoverflow.com/a/52265733"
Bad reference, looks like it came from the `Countries` module.

2020-12-15 11:03 UTC, ukutaht commented on lib/plausible_web/templates/layout/app.html.eex
> +                <%= img_tag(PlausibleWeb.Router.Helpers.static_path(@conn, "/images/icon/plausible_logo_dark.png"), class: "h-8 w-auto sm:h-10 -mt-2 hideOnLight", alt: "Plausible logo")%>
Rather, `inline dark:block`. I just saw the the `hideOnLight` class makes the item inline not block

2020-12-15 11:07 UTC, Vigasaurus commented on assets/js/dashboard/stats/countries.js
> +    if (this.props.darkTheme !== prevProps.darkTheme) {
Yeah, we could. The only reason I added it like this was for system-following, in that if a user was on follow system and changed it system-wide, it would update immediately and not wait till a refresh. I don't think it would ultimately hurt to make it refresh only, but I just figured having it be immediately responsive could be better UX

2020-12-15 11:07 UTC, Vigasaurus commented on lib/plausible_web/templates/auth/password_reset_request_form.html.eex
> +      <%# TODO %>
Ah yeah I actually forgot about that - it's actually pretty trivial, I'll get it added.

2020-12-15 11:08 UTC, Vigasaurus commented on lib/plausible_web/templates/layout/app.html.eex
> +                <%= img_tag(PlausibleWeb.Router.Helpers.static_path(@conn, "/images/icon/plausible_logo_dark.png"), class: "h-8 w-auto sm:h-10 -mt-2 hideOnLight", alt: "Plausible logo")%>
Yeah we definitely could do tailwind utilities, I'm actually pretty unsure why I didn't. I guess that's what I get for doing things at 5am

2020-12-15 11:11 UTC, Vigasaurus commented
👍 all comments make sense, I'll get em resolved tomorrow (in like 8-10 hours probably) - and I've got the new stuff on master almost done anyways.

2020-12-15 11:13 UTC, ukutaht commented
> +1 all comments make sense, I'll get em resolved tomorrow (in like 8-10 hours probably) - and I've got the new stuff on master almost done anyways.

Of course, no pressure. If you don't finish it by tomorrow that's no problem. We are incredibly thankful for your contributions!

2020-12-15 21:07 UTC, Vigasaurus commented
This should be all good to go - I'll likely do another once-over to see if I missed anything with the added stuff/conflic resolution, but it should be ready :D

2020-12-16 09:34 UTC, ukutaht commented on assets/js/dashboard/stats/countries.js
> +    if (this.props.darkTheme !== prevProps.darkTheme) {
:+1:

2020-12-16 09:34 UTC, ukutaht commented
> Remove 'CountriesWrapper' from here.
> 
> And are you using 4 spaces? The rest of the project is 2 spaces, let's try to keep it consistent.

Updates look good. I will merge once formatting issues are solved

2020-12-16 09:39 UTC, Vigasaurus commented
Yeah, I was using tabs, I would've assumed that VS Code would've picked the same indent style as the rest of the repo 🤷‍♂️ whoops. 
Both issues fixed.

2020-12-16 09:56 UTC, ukutaht approved these changes

2020-12-16 09:57 UTC, ukutaht commented
Thank you so much @Vigasaurus! This is a big job done well.

I will deploy this later today 🚀🚀🚀🚀

2020-12-16 09:57 UTC, merged

2020-12-16 10:02 UTC, metmarkosaric commented
nice!! looking forward to announcing this to the community and putting @Vigasaurus in our hall of fame list of contributors!