Add return_to behaviour to 404 -> login flow
plausible/analytics pull request #4916
Opened 2024-12-17 14:54 UTC by ukutaht

### Changes

It's quite annoying at the moment to:
1. Receive a link to a dashboard (maybe with filters)
2. Get 404
3. Go to login
4. Enter credentials
5. Be redirected to /sites instead of the original link

This PR implements a `return_to` query param used in login flow, including when 2fa challenge is presented. This way the user lands on the intended page.

We currently have a session-based `login_dest` variable but it only works for known routes which dashboards are not. It could have been extended for this use-case but I felt like using query params is better when session state isn't strictly necessary.

2024-12-17 15:05 UTC, ukutaht commented on lib/plausible_web/templates/error/404_error.html.heex
> +  <%= if !@conn.assigns[:current_user] do %>
The CTA to log in only makes sense if there is no current user

2024-12-18 09:29 UTC, zoldar reviewed
Looks good - left some minor suggestions. Before the final 🦭 I'll take it for a short spin on preview app though.

2024-12-18 09:29 UTC, zoldar commented on lib/plausible_web/templates/error/404_error.html.heex
> +    <% end %>
As it's heex already, we can use a bit less noisy syntax here:

```suggestion

  <div :if={!@conn.assigns[:current_user]} class="text-xl dark:text-gray-100">
    Trying to access your dashboard? You may need to log in again to see it
  </div>
  <div class="mt-4 flex">
    <.button_link
      :if={!@conn.assigns[:current_user]}
      href={Routes.auth_path(@conn, :login_form, return_to: url_path(@conn))}
      class="mr-4"
    >
      Log in
    </.button_link>
```

2024-12-18 09:29 UTC, zoldar commented on lib/plausible_web/templates/auth/login_form.html.heex
> +    <.input type="hidden" field={f[:return_to]} value={@conn.assigns[:return_to]} />
I'm not 100% sure now, but given "return_to" always comes in params, this could be just:

```
<.input type="hidden" field={f[:return_to]} />
```

and we could stop passing it around explicitly in assigns maybe? 🤔

2024-12-18 09:29 UTC, zoldar commented on lib/plausible_web/controllers/auth_controller.ex
> +  def verify_2fa_form(conn, params) do
I assume verify_2fa_recovery_code(_form) is omitted intentionally as an edge case not worth covering?

2024-12-18 09:48 UTC, zoldar commented on lib/plausible_web/templates/auth/login_form.html.heex
> +    <.input type="hidden" field={f[:return_to]} value={@conn.assigns[:return_to]} />
This might also help with cases where we miss to pass the param around to assigns, like failed verify_2fa code submission - we loose `return_to` param there. This will be definitely more common than 2FA recovery code case 😅

2024-12-18 10:04 UTC, apata requested changes
@ukutaht I'm a bit concerned that as-is this can be used to craft malicious links. 
https://pr-4916.review.plausible.io/login?return_to=https:%2F%2Fexample.com%2Fhack%2Fplausible.io
If on the return URL is a copy of the Plausible login page, the user may naively enter their details again, inadvertently sharing their details with a hacker.

2024-12-18 10:14 UTC, zoldar commented
@apata good point. The `return_to` URL could be sanitized before final redirect, scraping any with non-matching host part.

2024-12-18 19:37 UTC, ukutaht commented on lib/plausible_web/templates/auth/login_form.html.heex
> +    <.input type="hidden" field={f[:return_to]} value={@conn.assigns[:return_to]} />
> and we could stop passing it around explicitly in assigns maybe? 🤔

Ah yes, super nice! I didn't realize forms worked this way. I've removed the explicit assigns. I've also made sure that `return_to` is carried along in the failed form submissions: https://github.com/plausible/analytics/pull/4916/commits/b4448bd6ad70d8e3d650e8af2e62c81e5a1251df

2024-12-18 19:38 UTC, ukutaht commented on lib/plausible_web/controllers/auth_controller.ex
> +  def verify_2fa_form(conn, params) do
Yes, exactly.

2024-12-18 19:59 UTC, ukutaht commented
> I'm a bit concerned that as-is this can be used to craft malicious links.

Thanks, that's a good point! I've taken a stab at it [here](https://github.com/plausible/analytics/pull/4916/commits/2aced045dde3126df705567f69b0032dab329763). A few points about this commit:
* It changes the `Phoenix.Controller.redirect` function call to use `to: ` argument over `external: ` which only allows local redirects
* When an external URL is provided to `redirect` it will crash with a 500. Should be rare but still bad UX that I wanted to avoid. So I added a small validation our side as well which will ignore `return_to` unless it starts with a `"/"`
* Note that it's still possible to craft a malicious URL that starts with a double slash `"//"`, and in that case we will 500 but I don't expect this to happen often if at all
* @zoldar is there any reason we've been using `external` over `to? I'm not sure why we would need to redirect to an external URL here...

2024-12-19 08:39 UTC, zoldar commented
@ukutaht 

Ad 5. this was originally a workaround for issue with internal redirects failing when there's a url encoded UTF8 character in the path (the domain of the site, in particular): https://github.com/plausible/analytics/pull/3560 - phoenix was validating the "to" URLs a bit overzealously. The phoenix version we currently are on (1.7.14) has this behavior changed via https://github.com/phoenixframework/phoenix/commit/4ca6ca200973c940a7e412404e735fba9d56640e. This should no longer be an issue and we should be able to get back to using internal "to" redirects.

2024-12-19 09:02 UTC, apata commented
I'm happy with that, @ukutaht! But because this feature allows redirecting to a page that has itself url search params (https://pr-4916.review.plausible.io/login?return_to=/sites%3Ffoo%3Dbar), any other open redirect vulnerability that we might have would still be exploitable. Before we release it, we should double check that we don't have any.

2024-12-30 16:09 UTC, ukutaht commented
Thanks both @zoldar @apata. If it's good to go from your side @apata please change your review to approved so this can be merged :)

2025-01-02 10:56 UTC, apata approved these changes

2025-01-02 10:59 UTC, apata commented
Sorry for the wait, @ukutaht! I think I was actually expecting to see a fix on the failing CI checks, but then I forgot about the whole thing for the holidays.

2025-01-14 12:02 UTC, merged