Allows middle-click and ctrl+click outbound clicks to properly open as user intended
plausible/analytics pull request #494
Opened 2020-12-21 07:04 UTC by Vigasaurus

### Changes

Allows middle clicks or ctrl+click, cmd+click, shift+click to track to plausible, and open in a new tab if requested, instead of always redirecting the current tab. 

Fixes #451 

This will almost certainly cause conflicts with #489 in the compiled script, so I didn't push them in this PR at all. Once both are merged we can re-compile the merged version. 

### Tests
- [X] This PR does not require tests

### Changelog
- [ ] Entry has been added to changelog

### Documentation
- [X] This change does not need a documentation update

2020-12-21 13:19 UTC, ukutaht requested changes
Nice way to account for middle clicks as well. Looks like formatting is a bit off and I'm curious what the purpose of `window.open` is when middle click or modifier is used.

2020-12-21 13:19 UTC, ukutaht commented on tracker/src/plausible.js
> +    var click = event.type == "click";
What's going on with the spacing here? Seems like this line is 1 space to the left of the next line which cannot be correct.

2020-12-21 13:19 UTC, ukutaht commented on tracker/src/plausible.js
> +          if (middle || event.ctrlKey || event.metaKey || event.shiftKey) window.open(link.href)
What does this line do? When someone uses middle click on `cmd+click`, I would expect we do nothing here and allow default browser behaviour.

2020-12-21 13:19 UTC, ukutaht commented on tracker/src/plausible.js
> +          if (middle || event.ctrlKey || event.metaKey || event.shiftKey) window.open(link.href)
Oh, the if-else statement is formatted inconsistently

2020-12-21 19:16 UTC, Vigasaurus commented
So the reason for using window.open is that browsers interpret middle clicks as "Open in New Tab", the same as ctrl+click or cmd+click - and in the old way we'd always redirect the current tab to the new link. This way ensures that if a user does any of the actions that would normally redirect their click into a new tab (middle click, ctrl+click, cmd+click, or shift+click) - we open a new tab for the link as expected, as opposed to redirecting the current tab.

2020-12-22 13:56 UTC, ukutaht approved these changes

2020-12-22 13:57 UTC, merged