Allow for `Esc` to clear all filters
plausible/analytics pull request #625
Opened 2021-01-20 08:29 UTC by Vigasaurus

### Changes

Resolves #575

### Tests
- [X] This PR does not require tests

### Changelog
- [ ] Entry has been added to changelog
Same as my other PRs heh - lmk what you want for changelog format and I'll get it sorted

### Documentation
- [ ] [Docs](https://github.com/plausible/docs) have been updated
- [ ] This change does not need a documentation update
🤷‍♂️

2021-01-20 08:35 UTC, metmarkosaric commented
Nice! Our keyboard shortcuts game is getting stronger! I like it!

2021-01-20 08:42 UTC, Vigasaurus commented
I'm actually considering something else too, but I did actually want y'all's feedback/opinions. 
![firefox_2021-01-16_01-34-31](https://user-images.githubusercontent.com/19434157/105149170-dea13d00-5ac8-11eb-8d95-afa6a3636a1a.png)

I don't know that actually showing them here is necessary, but I thought something like this very similar to how calendar apps work could be neat. (This is just a mock up made in paint)
For the Custom I thought it would be cool for it to just open up the Calendar input automatically, and for the others to do what you'd expect (i.e. exactly what clicking the button would do)

2021-01-20 08:49 UTC, metmarkosaric commented
that's very cool and i was thinking to share that idea. i didn't know it's a google calendar thing but last week we started using Hey for email and they do that everywhere and I really like it (just need to get used to the different keybindings)

![Screenshot from 2021-01-20 09-47-25](https://user-images.githubusercontent.com/34340819/105150180-b7686100-5b04-11eb-9d02-6fbe398de66c.png)

2021-01-20 08:59 UTC, Vigasaurus commented
Sounds good (I've always been meaning to try hey but ... lazy)! How do you feel about the following, then? I think some of the more obscure ones don't need a binding, but lmk if you think there should be one for any. 

Dropdown Action | Keybind
--|--
Today | D
Realtime | R
Last 7 days | W
Last 30 days |
Month to Date | M
Last month |
Last 6 months | 
Last 12 months | Y
Custom range | C

2021-01-20 09:05 UTC, metmarkosaric commented
looks good to me @Vigasaurus! good that it follows google calendar as i assume that may be the standard that's used in more apps too.

2021-01-20 13:52 UTC, ukutaht requested changes
Feel free to add to the `1.2 - unreleased` section on the changelog.

2021-01-20 13:52 UTC, ukutaht commented on assets/js/dashboard/filters.js
> +    if (e.ctrlKey || e.ctrlKey || e.altKey) return
Seems like `ctrlKey` is checked for twice

2021-01-20 16:09 UTC, Vigasaurus commented on assets/js/dashboard/filters.js
> +    if (e.ctrlKey || e.ctrlKey || e.altKey) return
Ah haha - I just copied this from the DatePicker arrows, didn't even notice 🙈

2021-01-21 13:11 UTC, ukutaht approved these changes

2021-01-21 13:11 UTC, merged